// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumLinksService handles Forum Links API endpoints.
type ForumLinksService struct {
	client *httpClient
}

// Get Get Link Forum
func (s *ForumLinksService) Get(ctx context.Context, linkID int64) (*ForumLinksGetResponse, error) {
	var result ForumLinksGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/link-forums/%d", linkID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Links Forum
func (s *ForumLinksService) List(ctx context.Context) (*ForumLinksListResponse, error) {
	var result ForumLinksListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/link-forums",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
