// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumPagesService handles Forum Pages API endpoints.
type ForumPagesService struct {
	client *httpClient
}

// Get Get Page
func (s *ForumPagesService) Get(ctx context.Context, pageID int64) (*ForumPagesGetResponse, error) {
	var result ForumPagesGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/pages/%d", pageID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Pages
func (s *ForumPagesService) List(ctx context.Context, params *ForumPagesListParams) (*ForumPagesListResponse, error) {
	var result ForumPagesListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/pages",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
