// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumProfilePostsService handles Forum ProfilePosts API endpoints.
type ForumProfilePostsService struct {
	client *httpClient
}

// CommentsCreate Create Profile Post Comment
func (s *ForumProfilePostsService) CommentsCreate(ctx context.Context, body *ForumProfilePostsCommentsCreateBody) (*ForumProfilePostsCommentsCreateResponse, error) {
	var result ForumProfilePostsCommentsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsDelete Delete Profile Post Comment
func (s *ForumProfilePostsService) CommentsDelete(ctx context.Context, body *ForumProfilePostsCommentsDeleteBody) (*ForumProfilePostsCommentsDeleteResponse, error) {
	var result ForumProfilePostsCommentsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsEdit Edit Profile Post Comment
func (s *ForumProfilePostsService) CommentsEdit(ctx context.Context, body *ForumProfilePostsCommentsEditBody) (*ForumProfilePostsCommentsEditResponse, error) {
	var result ForumProfilePostsCommentsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsGet Get Profile Post Comment
func (s *ForumProfilePostsService) CommentsGet(ctx context.Context, profilePostID int64, commentID int64) (*ForumProfilePostsCommentsGetResponse, error) {
	var result ForumProfilePostsCommentsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/comments/%d", profilePostID, commentID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsList Get Profile Post Comments
func (s *ForumProfilePostsService) CommentsList(ctx context.Context, params *ForumProfilePostsCommentsListParams) (*ForumProfilePostsCommentsListResponse, error) {
	var result ForumProfilePostsCommentsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/profile-posts/comments",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsReport Report a Profile Post Comment
func (s *ForumProfilePostsService) CommentsReport(ctx context.Context, commentID int64, body *ForumProfilePostsCommentsReportBody) (*ForumProfilePostsCommentsReportResponse, error) {
	var result ForumProfilePostsCommentsReportResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/comments/%d/report", commentID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Profile Post
func (s *ForumProfilePostsService) Create(ctx context.Context, body *ForumProfilePostsCreateBody) (*ForumProfilePostsCreateResponse, error) {
	var result ForumProfilePostsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/profile-posts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Profile Post
func (s *ForumProfilePostsService) Delete(ctx context.Context, profilePostID int64, params *ForumProfilePostsDeleteParams) (*ForumProfilePostsDeleteResponse, error) {
	var result ForumProfilePostsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Profile Post
func (s *ForumProfilePostsService) Edit(ctx context.Context, profilePostID int64, body *ForumProfilePostsEditBody) (*ForumProfilePostsEditResponse, error) {
	var result ForumProfilePostsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Profile Post
func (s *ForumProfilePostsService) Get(ctx context.Context, profilePostID int64) (*ForumProfilePostsGetResponse, error) {
	var result ForumProfilePostsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Like Like Profile Post
func (s *ForumProfilePostsService) Like(ctx context.Context, profilePostID int64) (*ForumProfilePostsLikeResponse, error) {
	var result ForumProfilePostsLikeResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get Profile Post Likes
func (s *ForumProfilePostsService) Likes(ctx context.Context, profilePostID int64) (*ForumProfilePostsLikesResponse, error) {
	var result ForumProfilePostsLikesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Profile Posts
func (s *ForumProfilePostsService) List(ctx context.Context, userID any, params *ForumProfilePostsListParams) (*ForumProfilePostsListResponse, error) {
	var result ForumProfilePostsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/profile-posts", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report a Profile Post
func (s *ForumProfilePostsService) Report(ctx context.Context, profilePostID int64, body *ForumProfilePostsReportBody) (*ForumProfilePostsReportResponse, error) {
	var result ForumProfilePostsReportResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/report", profilePostID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Profile Post Report Reasons
func (s *ForumProfilePostsService) ReportReasons(ctx context.Context, profilePostID int64) (*ForumProfilePostsReportReasonsResponse, error) {
	var result ForumProfilePostsReportReasonsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/report", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stick Stick Profile Post
func (s *ForumProfilePostsService) Stick(ctx context.Context, profilePostID int64) (*ForumProfilePostsStickResponse, error) {
	var result ForumProfilePostsStickResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/stick", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unlike Unlike Profile Post
func (s *ForumProfilePostsService) Unlike(ctx context.Context, profilePostID int64) (*ForumProfilePostsUnlikeResponse, error) {
	var result ForumProfilePostsUnlikeResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstick Unstick Profile Post
func (s *ForumProfilePostsService) Unstick(ctx context.Context, profilePostID int64) (*ForumProfilePostsUnstickResponse, error) {
	var result ForumProfilePostsUnstickResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d/stick", profilePostID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
