// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumAssetsService handles Forum Assets API endpoints.
type ForumAssetsService struct {
	client *httpClient
}

// CSS Get CSS
func (s *ForumAssetsService) CSS(ctx context.Context, params *ForumAssetsCSSParams) (*ForumAssetsCSSResponse, error) {
	var result ForumAssetsCSSResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/css",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
