// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumSearchService handles Forum Search API endpoints.
type ForumSearchService struct {
	client *httpClient
}

// All Search
func (s *ForumSearchService) All(ctx context.Context, body *ForumSearchAllBody) (*ForumSearchAllResponse, error) {
	var result ForumSearchAllResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Posts Search Post
func (s *ForumSearchService) Posts(ctx context.Context, body *ForumSearchPostsBody) (*ForumSearchPostsResponse, error) {
	var result ForumSearchPostsResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search/posts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ProfilePosts Search Profile Posts
func (s *ForumSearchService) ProfilePosts(ctx context.Context, body *ForumSearchProfilePostsBody) (*ForumSearchProfilePostsResponse, error) {
	var result ForumSearchProfilePostsResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search/profile-posts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Results Get Search Results
func (s *ForumSearchService) Results(ctx context.Context, searchID any, params *ForumSearchResultsParams) (*ForumSearchResultsResponse, error) {
	var result ForumSearchResultsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/search/%v/results", searchID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Tagged Search Tagged
func (s *ForumSearchService) Tagged(ctx context.Context, body *ForumSearchTaggedBody) (*ForumSearchTaggedResponse, error) {
	var result ForumSearchTaggedResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search/tagged",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Threads Search Thread
func (s *ForumSearchService) Threads(ctx context.Context, body *ForumSearchThreadsBody) (*ForumSearchThreadsResponse, error) {
	var result ForumSearchThreadsResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search/threads",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Users Search Users
func (s *ForumSearchService) Users(ctx context.Context, body *ForumSearchUsersBody) (*ForumSearchUsersResponse, error) {
	var result ForumSearchUsersResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/search/users",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
