// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumOAuthService handles Forum OAuth API endpoints.
type ForumOAuthService struct {
	client *httpClient
}

// Token Get Access Token
func (s *ForumOAuthService) Token(ctx context.Context, body *ForumOAuthTokenBody) (*ForumOAuthTokenResponse, error) {
	var result ForumOAuthTokenResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/oauth/token",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
