// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumConversationsService handles Forum Conversations API endpoints.
type ForumConversationsService struct {
	client *httpClient
}

// AlertsDisable Disable Conversation Alerts
func (s *ForumConversationsService) AlertsDisable(ctx context.Context, conversationID int64) (*ForumConversationsAlertsDisableResponse, error) {
	var result ForumConversationsAlertsDisableResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/alerts", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AlertsEnable Enable Conversation Alerts
func (s *ForumConversationsService) AlertsEnable(ctx context.Context, conversationID int64) (*ForumConversationsAlertsEnableResponse, error) {
	var result ForumConversationsAlertsEnableResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/alerts", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Conversation
func (s *ForumConversationsService) Create(ctx context.Context, body *ForumConversationsCreateBody) (*ForumConversationsCreateResponse, error) {
	var result ForumConversationsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/conversations",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Leave Conversation
func (s *ForumConversationsService) Delete(ctx context.Context, body *ForumConversationsDeleteBody) (*ForumConversationsDeleteResponse, error) {
	var result ForumConversationsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/conversations",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Conversation
func (s *ForumConversationsService) Get(ctx context.Context, conversationID int64) (*ForumConversationsGetResponse, error) {
	var result ForumConversationsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/%d", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Invite Invite Users to Conversation
func (s *ForumConversationsService) Invite(ctx context.Context, conversationID int64, body *ForumConversationsInviteBody) (*ForumConversationsInviteResponse, error) {
	var result ForumConversationsInviteResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/invite", conversationID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Kick Kick User from Conversation
func (s *ForumConversationsService) Kick(ctx context.Context, conversationID int64, body *ForumConversationsKickBody) (*ForumConversationsKickResponse, error) {
	var result ForumConversationsKickResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/kick", conversationID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Conversations
func (s *ForumConversationsService) List(ctx context.Context, params *ForumConversationsListParams) (*ForumConversationsListResponse, error) {
	var result ForumConversationsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/conversations",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesCreate Create Conversation Message
func (s *ForumConversationsService) MessagesCreate(ctx context.Context, conversationID int64, body *ForumConversationsMessagesCreateBody) (*ForumConversationsMessagesCreateResponse, error) {
	var result ForumConversationsMessagesCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/messages", conversationID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesDelete Delete Conversation Message
func (s *ForumConversationsService) MessagesDelete(ctx context.Context, conversationID int64, messageID int64) (*ForumConversationsMessagesDeleteResponse, error) {
	var result ForumConversationsMessagesDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d", conversationID, messageID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesEdit Edit Conversation Message
func (s *ForumConversationsService) MessagesEdit(ctx context.Context, conversationID int64, messageID int64, body *ForumConversationsMessagesEditBody) (*ForumConversationsMessagesEditResponse, error) {
	var result ForumConversationsMessagesEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d", conversationID, messageID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesGet Get Conversation Message
func (s *ForumConversationsService) MessagesGet(ctx context.Context, messageID int64) (*ForumConversationsMessagesGetResponse, error) {
	var result ForumConversationsMessagesGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/messages/%d", messageID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesList Get Conversation Messages
func (s *ForumConversationsService) MessagesList(ctx context.Context, conversationID int64, params *ForumConversationsMessagesListParams) (*ForumConversationsMessagesListResponse, error) {
	var result ForumConversationsMessagesListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/%d/messages", conversationID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesStick Stick Conversation Message
func (s *ForumConversationsService) MessagesStick(ctx context.Context, conversationID int64, messageID int64) (*ForumConversationsMessagesStickResponse, error) {
	var result ForumConversationsMessagesStickResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d/stick", conversationID, messageID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesUnstick Unstick Conversation Message
func (s *ForumConversationsService) MessagesUnstick(ctx context.Context, conversationID int64, messageID int64) (*ForumConversationsMessagesUnstickResponse, error) {
	var result ForumConversationsMessagesUnstickResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d/stick", conversationID, messageID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Read Read a Conversation
func (s *ForumConversationsService) Read(ctx context.Context, conversationID int64) (*ForumConversationsReadResponse, error) {
	var result ForumConversationsReadResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/read", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReadAll Read All Conversations
func (s *ForumConversationsService) ReadAll(ctx context.Context) (*ForumConversationsReadAllResponse, error) {
	var result ForumConversationsReadAllResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/conversations/read-all",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Save Send Content To Saved Messages
func (s *ForumConversationsService) Save(ctx context.Context, body *ForumConversationsSaveBody) (*ForumConversationsSaveResponse, error) {
	var result ForumConversationsSaveResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/conversations/save",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Search Search Conversations Messages
func (s *ForumConversationsService) Search(ctx context.Context, body *ForumConversationsSearchBody) (*ForumConversationsSearchResponse, error) {
	var result ForumConversationsSearchResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/conversations/search",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Star Star Conversation
func (s *ForumConversationsService) Star(ctx context.Context, conversationID int64) (*ForumConversationsStarResponse, error) {
	var result ForumConversationsStarResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/star", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Start Start Conversation
func (s *ForumConversationsService) Start(ctx context.Context, body *ForumConversationsStartBody) (*ForumConversationsStartResponse, error) {
	var result ForumConversationsStartResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/conversations/start",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstar Unstar Conversation
func (s *ForumConversationsService) Unstar(ctx context.Context, conversationID int64) (*ForumConversationsUnstarResponse, error) {
	var result ForumConversationsUnstarResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/star", conversationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Update Edit Conversation
func (s *ForumConversationsService) Update(ctx context.Context, body *ForumConversationsUpdateBody) (*ForumConversationsUpdateResponse, error) {
	var result ForumConversationsUpdateResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/conversations",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
