// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumBatchService handles Forum Batch API endpoints.
type ForumBatchService struct {
	client *httpClient
}

// Execute Batch
func (s *ForumBatchService) Execute(ctx context.Context, jobs []ForumBatchExecuteItem) (*ForumBatchExecuteResponse, error) {
	var result ForumBatchExecuteResponse
	opts := requestOptions{
		Method:  "POST",
		Path:    "/batch",
		RawJSON: jobs,
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
