// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumTagsService handles Forum Tags API endpoints.
type ForumTagsService struct {
	client *httpClient
}

// Find Get Filtered Content
func (s *ForumTagsService) Find(ctx context.Context, params *ForumTagsFindParams) (*ForumTagsFindResponse, error) {
	var result ForumTagsFindResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/tags/find",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Tagged Content
func (s *ForumTagsService) Get(ctx context.Context, tagID int64, params *ForumTagsGetParams) (*ForumTagsGetResponse, error) {
	var result ForumTagsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/tags/%d", tagID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Tags
func (s *ForumTagsService) List(ctx context.Context, params *ForumTagsListParams) (*ForumTagsListResponse, error) {
	var result ForumTagsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/tags/list",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Popular Get Popular Tags
func (s *ForumTagsService) Popular(ctx context.Context) (*ForumTagsPopularResponse, error) {
	var result ForumTagsPopularResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/tags",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
