// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

// ForumClient provides access to the Lolzteam Forum API.
type ForumClient struct {
	Assets        *ForumAssetsService
	Batch         *ForumBatchService
	Categories    *ForumCategoriesService
	Chatbox       *ForumChatboxService
	Conversations *ForumConversationsService
	Forms         *ForumFormsService
	Forums        *ForumForumsService
	Links         *ForumLinksService
	Navigation    *ForumNavigationService
	Notifications *ForumNotificationsService
	OAuth         *ForumOAuthService
	Pages         *ForumPagesService
	Posts         *ForumPostsService
	ProfilePosts  *ForumProfilePostsService
	Search        *ForumSearchService
	Tags          *ForumTagsService
	Threads       *ForumThreadsService
	Users         *ForumUsersService
}

// NewForumClient creates a new Forum API client.
func NewForumClient(config Config) *ForumClient {
	if config.BaseURL == "" {
		config.BaseURL = "https://api.lolz.live"
	}
	if config.RequestsPerMinute == 0 {
		config.RequestsPerMinute = 300
	}
	c := newHTTPClient(config)
	return &ForumClient{
		Assets:        &ForumAssetsService{client: c},
		Batch:         &ForumBatchService{client: c},
		Categories:    &ForumCategoriesService{client: c},
		Chatbox:       &ForumChatboxService{client: c},
		Conversations: &ForumConversationsService{client: c},
		Forms:         &ForumFormsService{client: c},
		Forums:        &ForumForumsService{client: c},
		Links:         &ForumLinksService{client: c},
		Navigation:    &ForumNavigationService{client: c},
		Notifications: &ForumNotificationsService{client: c},
		OAuth:         &ForumOAuthService{client: c},
		Pages:         &ForumPagesService{client: c},
		Posts:         &ForumPostsService{client: c},
		ProfilePosts:  &ForumProfilePostsService{client: c},
		Search:        &ForumSearchService{client: c},
		Tags:          &ForumTagsService{client: c},
		Threads:       &ForumThreadsService{client: c},
		Users:         &ForumUsersService{client: c},
	}
}
