// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumChatboxService handles Forum Chatbox API endpoints.
type ForumChatboxService struct {
	client *httpClient
}

// DeleteIgnore Unignore Chat User
func (s *ForumChatboxService) DeleteIgnore(ctx context.Context, body *ForumChatboxDeleteIgnoreBody) (*ForumChatboxDeleteIgnoreResponse, error) {
	var result ForumChatboxDeleteIgnoreResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/chatbox/ignore",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteMessage Delete Chat Message
func (s *ForumChatboxService) DeleteMessage(ctx context.Context, body *ForumChatboxDeleteMessageBody) (*ForumChatboxDeleteMessageResponse, error) {
	var result ForumChatboxDeleteMessageResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EditMessage Edit Chat Message
func (s *ForumChatboxService) EditMessage(ctx context.Context, body *ForumChatboxEditMessageBody) (*ForumChatboxEditMessageResponse, error) {
	var result ForumChatboxEditMessageResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetIgnore Get Ignored Chat Users
func (s *ForumChatboxService) GetIgnore(ctx context.Context) (*ForumChatboxGetIgnoreResponse, error) {
	var result ForumChatboxGetIgnoreResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox/ignore",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetLeaderboard Get Chat Leaderboard
func (s *ForumChatboxService) GetLeaderboard(ctx context.Context, params *ForumChatboxGetLeaderboardParams) (*ForumChatboxGetLeaderboardResponse, error) {
	var result ForumChatboxGetLeaderboardResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/leaderboard",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetMessages Get Chat Messages
func (s *ForumChatboxService) GetMessages(ctx context.Context, params *ForumChatboxGetMessagesParams) (*ForumChatboxGetMessagesResponse, error) {
	var result ForumChatboxGetMessagesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox/messages",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Index Get Chats
func (s *ForumChatboxService) Index(ctx context.Context, params *ForumChatboxIndexParams) (*ForumChatboxIndexResponse, error) {
	var result ForumChatboxIndexResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Online Get Chat Online
func (s *ForumChatboxService) Online(ctx context.Context, params *ForumChatboxOnlineParams) (*ForumChatboxOnlineResponse, error) {
	var result ForumChatboxOnlineResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/online",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PostIgnore Ignore Chat User
func (s *ForumChatboxService) PostIgnore(ctx context.Context, body *ForumChatboxPostIgnoreBody) (*ForumChatboxPostIgnoreResponse, error) {
	var result ForumChatboxPostIgnoreResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/chatbox/ignore",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PostMessage Create Chat Message
func (s *ForumChatboxService) PostMessage(ctx context.Context, body *ForumChatboxPostMessageBody) (*ForumChatboxPostMessageResponse, error) {
	var result ForumChatboxPostMessageResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report Chat Message
func (s *ForumChatboxService) Report(ctx context.Context, body *ForumChatboxReportBody) (*ForumChatboxReportResponse, error) {
	var result ForumChatboxReportResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/chatbox/messages/report",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Chat Message Report Reasons
func (s *ForumChatboxService) ReportReasons(ctx context.Context, params *ForumChatboxReportReasonsParams) (*ForumChatboxReportReasonsResponse, error) {
	var result ForumChatboxReportReasonsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/report",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
