// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumNavigationService handles Forum Navigation API endpoints.
type ForumNavigationService struct {
	client *httpClient
}

// List Get Navigation
func (s *ForumNavigationService) List(ctx context.Context, params *ForumNavigationListParams) (*ForumNavigationListResponse, error) {
	var result ForumNavigationListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/navigation",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
