// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// ForumFormsService handles Forum Forms API endpoints.
type ForumFormsService struct {
	client *httpClient
}

// Create Create Form
func (s *ForumFormsService) Create(ctx context.Context, body *ForumFormsCreateBody) (*ForumFormsCreateResponse, error) {
	var result ForumFormsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/forms/save",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Forms List
func (s *ForumFormsService) List(ctx context.Context, params *ForumFormsListParams) (*ForumFormsListResponse, error) {
	var result ForumFormsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/forms",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
