// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumCategoriesService handles Forum Categories API endpoints.
type ForumCategoriesService struct {
	client *httpClient
}

// Get Get Category
func (s *ForumCategoriesService) Get(ctx context.Context, categoryID int64) (*ForumCategoriesGetResponse, error) {
	var result ForumCategoriesGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/categories/%d", categoryID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Categories
func (s *ForumCategoriesService) List(ctx context.Context, params *ForumCategoriesListParams) (*ForumCategoriesListResponse, error) {
	var result ForumCategoriesListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/categories",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
