// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumUsersService handles Forum Users API endpoints.
type ForumUsersService struct {
	client *httpClient
}

// AvatarCrop Crop Avatar
func (s *ForumUsersService) AvatarCrop(ctx context.Context, userID any, body *ForumUsersAvatarCropBody) (*ForumUsersAvatarCropResponse, error) {
	var result ForumUsersAvatarCropResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/avatar/crop", userID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AvatarDelete Delete Avatar
func (s *ForumUsersService) AvatarDelete(ctx context.Context, userID any) (*ForumUsersAvatarDeleteResponse, error) {
	var result ForumUsersAvatarDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%v/avatar", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AvatarUpload Upload Avatar
func (s *ForumUsersService) AvatarUpload(ctx context.Context, userID any, body *ForumUsersAvatarUploadBody) (*ForumUsersAvatarUploadResponse, error) {
	var result ForumUsersAvatarUploadResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/avatar", userID),
	}
	if body != nil {
		opts.Multipart = structToMultipart(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundCrop Crop Background
func (s *ForumUsersService) BackgroundCrop(ctx context.Context, userID any, body *ForumUsersBackgroundCropBody) (*ForumUsersBackgroundCropResponse, error) {
	var result ForumUsersBackgroundCropResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/background/crop", userID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundDelete Delete Background
func (s *ForumUsersService) BackgroundDelete(ctx context.Context, userID any) (*ForumUsersBackgroundDeleteResponse, error) {
	var result ForumUsersBackgroundDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%v/background", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundUpload Upload Background
func (s *ForumUsersService) BackgroundUpload(ctx context.Context, userID any, body *ForumUsersBackgroundUploadBody) (*ForumUsersBackgroundUploadResponse, error) {
	var result ForumUsersBackgroundUploadResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/background", userID),
	}
	if body != nil {
		opts.Multipart = structToMultipart(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Claims Get User Claims
func (s *ForumUsersService) Claims(ctx context.Context, userID any, params *ForumUsersClaimsParams) (*ForumUsersClaimsResponse, error) {
	var result ForumUsersClaimsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/claims", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Contents Get Contents
func (s *ForumUsersService) Contents(ctx context.Context, userID any, params *ForumUsersContentsParams) (*ForumUsersContentsResponse, error) {
	var result ForumUsersContentsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/timeline", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit User
func (s *ForumUsersService) Edit(ctx context.Context, userID any, body *ForumUsersEditBody) (*ForumUsersEditResponse, error) {
	var result ForumUsersEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/users/%v", userID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fields Get User Fields
func (s *ForumUsersService) Fields(ctx context.Context) (*ForumUsersFieldsResponse, error) {
	var result ForumUsersFieldsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/users/fields",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Find Find Users
func (s *ForumUsersService) Find(ctx context.Context, params *ForumUsersFindParams) (*ForumUsersFindResponse, error) {
	var result ForumUsersFindResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/users/find",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow User
func (s *ForumUsersService) Follow(ctx context.Context, userID any) (*ForumUsersFollowResponse, error) {
	var result ForumUsersFollowResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/followers", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get User Followers
func (s *ForumUsersService) Followers(ctx context.Context, userID any, params *ForumUsersFollowersParams) (*ForumUsersFollowersResponse, error) {
	var result ForumUsersFollowersResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/followers", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followings Get Followed Users By User
func (s *ForumUsersService) Followings(ctx context.Context, userID any, params *ForumUsersFollowingsParams) (*ForumUsersFollowingsResponse, error) {
	var result ForumUsersFollowingsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/followings", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get User
func (s *ForumUsersService) Get(ctx context.Context, userID any, params *ForumUsersGetParams) (*ForumUsersGetResponse, error) {
	var result ForumUsersGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ignore Ignore User
func (s *ForumUsersService) Ignore(ctx context.Context, userID any) (*ForumUsersIgnoreResponse, error) {
	var result ForumUsersIgnoreResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%v/ignore", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// IgnoreEdit Edit Ignoring Options
func (s *ForumUsersService) IgnoreEdit(ctx context.Context, userID any, params *ForumUsersIgnoreEditParams) (*ForumUsersIgnoreEditResponse, error) {
	var result ForumUsersIgnoreEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/users/%v/ignore", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ignored Get Ignored Users
func (s *ForumUsersService) Ignored(ctx context.Context, params *ForumUsersIgnoredParams) (*ForumUsersIgnoredResponse, error) {
	var result ForumUsersIgnoredResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/users/ignored",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get User Likes
func (s *ForumUsersService) Likes(ctx context.Context, userID any, params *ForumUsersLikesParams) (*ForumUsersLikesResponse, error) {
	var result ForumUsersLikesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/likes", userID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Users
func (s *ForumUsersService) List(ctx context.Context, params *ForumUsersListParams) (*ForumUsersListResponse, error) {
	var result ForumUsersListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/users",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SACancelReset Cancel Secret Answer Reset
func (s *ForumUsersService) SACancelReset(ctx context.Context) (*ForumUsersSACancelResetResponse, error) {
	var result ForumUsersSACancelResetResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/account/secret-answer/reset",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SAReset Reset Secret Answer
func (s *ForumUsersService) SAReset(ctx context.Context) (*ForumUsersSAResetResponse, error) {
	var result ForumUsersSAResetResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/account/secret-answer/reset",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SecretAnswerTypes Get Secret Answer Types
func (s *ForumUsersService) SecretAnswerTypes(ctx context.Context) (*ForumUsersSecretAnswerTypesResponse, error) {
	var result ForumUsersSecretAnswerTypesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/users/secret-answer/types",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Trophies Get Trophies
func (s *ForumUsersService) Trophies(ctx context.Context, userID any) (*ForumUsersTrophiesResponse, error) {
	var result ForumUsersTrophiesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%v/trophies", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow User
func (s *ForumUsersService) Unfollow(ctx context.Context, userID any) (*ForumUsersUnfollowResponse, error) {
	var result ForumUsersUnfollowResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%v/followers", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unignore Unignore User
func (s *ForumUsersService) Unignore(ctx context.Context, userID any) (*ForumUsersUnignoreResponse, error) {
	var result ForumUsersUnignoreResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%v/ignore", userID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
