// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumForumsService handles Forum Forums API endpoints.
type ForumForumsService struct {
	client *httpClient
}

// EditFeedOptions Edit Feed Options
func (s *ForumForumsService) EditFeedOptions(ctx context.Context, body *ForumForumsEditFeedOptionsBody) (*ForumForumsEditFeedOptionsResponse, error) {
	var result ForumForumsEditFeedOptionsResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/forums/feed/options",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow Forum
func (s *ForumForumsService) Follow(ctx context.Context, forumID int64, body *ForumForumsFollowBody) (*ForumForumsFollowResponse, error) {
	var result ForumForumsFollowResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followed Get Followed Forums
func (s *ForumForumsService) Followed(ctx context.Context, params *ForumForumsFollowedParams) (*ForumForumsFollowedResponse, error) {
	var result ForumForumsFollowedResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/forums/followed",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get Followers
func (s *ForumForumsService) Followers(ctx context.Context, forumID int64) (*ForumForumsFollowersResponse, error) {
	var result ForumForumsFollowersResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Forum
func (s *ForumForumsService) Get(ctx context.Context, forumID int64) (*ForumForumsGetResponse, error) {
	var result ForumForumsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/forums/%d", forumID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetFeedOptions Get Feed Options
func (s *ForumForumsService) GetFeedOptions(ctx context.Context) (*ForumForumsGetFeedOptionsResponse, error) {
	var result ForumForumsGetFeedOptionsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/forums/feed/options",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Grouped Get Forums Tree
func (s *ForumForumsService) Grouped(ctx context.Context) (*ForumForumsGroupedResponse, error) {
	var result ForumForumsGroupedResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/forums/grouped",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Forums
func (s *ForumForumsService) List(ctx context.Context, params *ForumForumsListParams) (*ForumForumsListResponse, error) {
	var result ForumForumsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/forums",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow Forum
func (s *ForumForumsService) Unfollow(ctx context.Context, forumID int64) (*ForumForumsUnfollowResponse, error) {
	var result ForumForumsUnfollowResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
