// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumPostsService handles Forum Posts API endpoints.
type ForumPostsService struct {
	client *httpClient
}

// CommentsCreate Create Post Comment
func (s *ForumPostsService) CommentsCreate(ctx context.Context, body *ForumPostsCommentsCreateBody) (*ForumPostsCommentsCreateResponse, error) {
	var result ForumPostsCommentsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsDelete Delete Post Comment
func (s *ForumPostsService) CommentsDelete(ctx context.Context, body *ForumPostsCommentsDeleteBody) (*ForumPostsCommentsDeleteResponse, error) {
	var result ForumPostsCommentsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsEdit Edit Post Comment
func (s *ForumPostsService) CommentsEdit(ctx context.Context, body *ForumPostsCommentsEditBody) (*ForumPostsCommentsEditResponse, error) {
	var result ForumPostsCommentsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsGet Get Post Comments
func (s *ForumPostsService) CommentsGet(ctx context.Context, params *ForumPostsCommentsGetParams) (*ForumPostsCommentsGetResponse, error) {
	var result ForumPostsCommentsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/posts/comments",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsReport Report Post Comment
func (s *ForumPostsService) CommentsReport(ctx context.Context, body *ForumPostsCommentsReportBody) (*ForumPostsCommentsReportResponse, error) {
	var result ForumPostsCommentsReportResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/posts/comments/report",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Post
func (s *ForumPostsService) Create(ctx context.Context, body *ForumPostsCreateBody) (*ForumPostsCreateResponse, error) {
	var result ForumPostsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/posts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Post
func (s *ForumPostsService) Delete(ctx context.Context, postID int64, body *ForumPostsDeleteBody) (*ForumPostsDeleteResponse, error) {
	var result ForumPostsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Post
func (s *ForumPostsService) Edit(ctx context.Context, postID int64, body *ForumPostsEditBody) (*ForumPostsEditResponse, error) {
	var result ForumPostsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Post
func (s *ForumPostsService) Get(ctx context.Context, postID int64) (*ForumPostsGetResponse, error) {
	var result ForumPostsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Like Like Post
func (s *ForumPostsService) Like(ctx context.Context, postID int64) (*ForumPostsLikeResponse, error) {
	var result ForumPostsLikeResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get Post Likes
func (s *ForumPostsService) Likes(ctx context.Context, postID int64, params *ForumPostsLikesParams) (*ForumPostsLikesResponse, error) {
	var result ForumPostsLikesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Posts
func (s *ForumPostsService) List(ctx context.Context, params *ForumPostsListParams) (*ForumPostsListResponse, error) {
	var result ForumPostsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/posts",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report Post
func (s *ForumPostsService) Report(ctx context.Context, postID int64, body *ForumPostsReportBody) (*ForumPostsReportResponse, error) {
	var result ForumPostsReportResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/posts/%d/report", postID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Post Report Reasons
func (s *ForumPostsService) ReportReasons(ctx context.Context, postID int64) (*ForumPostsReportReasonsResponse, error) {
	var result ForumPostsReportReasonsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d/report", postID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unlike Unlike Post
func (s *ForumPostsService) Unlike(ctx context.Context, postID int64) (*ForumPostsUnlikeResponse, error) {
	var result ForumPostsUnlikeResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
