// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumNotificationsService handles Forum Notifications API endpoints.
type ForumNotificationsService struct {
	client *httpClient
}

// Get Get Notification
func (s *ForumNotificationsService) Get(ctx context.Context, notificationID int64) (*ForumNotificationsGetResponse, error) {
	var result ForumNotificationsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/notifications/%d/content", notificationID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Notifications
func (s *ForumNotificationsService) List(ctx context.Context, params *ForumNotificationsListParams) (*ForumNotificationsListResponse, error) {
	var result ForumNotificationsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/notifications",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Read Mark Notification Read
func (s *ForumNotificationsService) Read(ctx context.Context, body *ForumNotificationsReadBody) (*ForumNotificationsReadResponse, error) {
	var result ForumNotificationsReadResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/notifications/read",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
