// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// ForumThreadsService handles Forum Threads API endpoints.
type ForumThreadsService struct {
	client *httpClient
}

// Bump Bump Thread
func (s *ForumThreadsService) Bump(ctx context.Context, threadID int64) (*ForumThreadsBumpResponse, error) {
	var result ForumThreadsBumpResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/bump", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Claim Create Claim
func (s *ForumThreadsService) Claim(ctx context.Context, body *ForumThreadsClaimBody) (*ForumThreadsClaimResponse, error) {
	var result ForumThreadsClaimResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/claims",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Thread
func (s *ForumThreadsService) Create(ctx context.Context, body *ForumThreadsCreateBody) (*ForumThreadsCreateResponse, error) {
	var result ForumThreadsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/threads",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateContest Create Contest
func (s *ForumThreadsService) CreateContest(ctx context.Context, body *ForumThreadsCreateContestBody) (*ForumThreadsCreateContestResponse, error) {
	var result ForumThreadsCreateContestResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/contests",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Thread
func (s *ForumThreadsService) Delete(ctx context.Context, threadID int64, body *ForumThreadsDeleteBody) (*ForumThreadsDeleteResponse, error) {
	var result ForumThreadsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit thread
func (s *ForumThreadsService) Edit(ctx context.Context, threadID int64, body *ForumThreadsEditBody) (*ForumThreadsEditResponse, error) {
	var result ForumThreadsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Finish Finish Contest
func (s *ForumThreadsService) Finish(ctx context.Context, threadID int64) (*ForumThreadsFinishResponse, error) {
	var result ForumThreadsFinishResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/contests/%d/finish", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow Thread
func (s *ForumThreadsService) Follow(ctx context.Context, threadID int64, body *ForumThreadsFollowBody) (*ForumThreadsFollowResponse, error) {
	var result ForumThreadsFollowResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followed Get Followed Threads
func (s *ForumThreadsService) Followed(ctx context.Context, params *ForumThreadsFollowedParams) (*ForumThreadsFollowedResponse, error) {
	var result ForumThreadsFollowedResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/threads/followed",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get Thread Followers
func (s *ForumThreadsService) Followers(ctx context.Context, threadID int64) (*ForumThreadsFollowersResponse, error) {
	var result ForumThreadsFollowersResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Thread
func (s *ForumThreadsService) Get(ctx context.Context, threadID int64, params *ForumThreadsGetParams) (*ForumThreadsGetResponse, error) {
	var result ForumThreadsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Hide Hide Thread
func (s *ForumThreadsService) Hide(ctx context.Context, threadID int64) (*ForumThreadsHideResponse, error) {
	var result ForumThreadsHideResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/hide", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Threads
func (s *ForumThreadsService) List(ctx context.Context, params *ForumThreadsListParams) (*ForumThreadsListResponse, error) {
	var result ForumThreadsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/threads",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Move Move Thread
func (s *ForumThreadsService) Move(ctx context.Context, threadID int64, body *ForumThreadsMoveBody) (*ForumThreadsMoveResponse, error) {
	var result ForumThreadsMoveResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/move", threadID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Navigation Get Navigation Elements
func (s *ForumThreadsService) Navigation(ctx context.Context, threadID int64) (*ForumThreadsNavigationResponse, error) {
	var result ForumThreadsNavigationResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/navigation", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PollGet Get Poll
func (s *ForumThreadsService) PollGet(ctx context.Context, threadID int64) (*ForumThreadsPollGetResponse, error) {
	var result ForumThreadsPollGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/poll", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PollVote Vote Poll
func (s *ForumThreadsService) PollVote(ctx context.Context, threadID int64, body *ForumThreadsPollVoteBody) (*ForumThreadsPollVoteResponse, error) {
	var result ForumThreadsPollVoteResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/poll/votes", threadID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Recent Get Recent Threads
func (s *ForumThreadsService) Recent(ctx context.Context, params *ForumThreadsRecentParams) (*ForumThreadsRecentResponse, error) {
	var result ForumThreadsRecentResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/threads/recent",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Star Bookmark Thread
func (s *ForumThreadsService) Star(ctx context.Context, threadID int64) (*ForumThreadsStarResponse, error) {
	var result ForumThreadsStarResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/star", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow Thread
func (s *ForumThreadsService) Unfollow(ctx context.Context, threadID int64) (*ForumThreadsUnfollowResponse, error) {
	var result ForumThreadsUnfollowResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unread Get Unread Threads
func (s *ForumThreadsService) Unread(ctx context.Context, params *ForumThreadsUnreadParams) (*ForumThreadsUnreadResponse, error) {
	var result ForumThreadsUnreadResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/threads/new",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstar Unbookmark Thread
func (s *ForumThreadsService) Unstar(ctx context.Context, threadID int64) (*ForumThreadsUnstarResponse, error) {
	var result ForumThreadsUnstarResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d/star", threadID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
