// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// MarketPublishingService handles Market Publishing API endpoints.
type MarketPublishingService struct {
	client *httpClient
}

// Add Add Account
func (s *MarketPublishingService) Add(ctx context.Context, body *MarketPublishingAddBody) (*MarketPublishingAddResponse, error) {
	var result MarketPublishingAddResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/item/add",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Check Check Account Details
func (s *MarketPublishingService) Check(ctx context.Context, itemID int64, body *MarketPublishingCheckBody) (*MarketPublishingCheckResponse, error) {
	var result MarketPublishingCheckResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/goods/check", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// External Add an External Account
func (s *MarketPublishingService) External(ctx context.Context, itemID int64, body *MarketPublishingExternalBody) (*MarketPublishingExternalResponse, error) {
	var result MarketPublishingExternalResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/external-account", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FastSell Fast Account Upload
func (s *MarketPublishingService) FastSell(ctx context.Context, body *MarketPublishingFastSellBody) (*MarketPublishingFastSellResponse, error) {
	var result MarketPublishingFastSellResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/item/fast-sell",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
