// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketAutoPaymentsService handles Market AutoPayments API endpoints.
type MarketAutoPaymentsService struct {
	client *httpClient
}

// Create Create Auto Payment
func (s *MarketAutoPaymentsService) Create(ctx context.Context, body *MarketAutoPaymentsCreateBody) (*MarketAutoPaymentsCreateResponse, error) {
	var result MarketAutoPaymentsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/auto-payment",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Auto Payment
func (s *MarketAutoPaymentsService) Delete(ctx context.Context, body *MarketAutoPaymentsDeleteBody) (*MarketAutoPaymentsDeleteResponse, error) {
	var result MarketAutoPaymentsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/auto-payment",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Auto Payments
func (s *MarketAutoPaymentsService) List(ctx context.Context) (*MarketAutoPaymentsListResponse, error) {
	var result MarketAutoPaymentsListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/auto-payments",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
