// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// MarketPurchasingService handles Market Purchasing API endpoints.
type MarketPurchasingService struct {
	client *httpClient
}

// Check Check Account
func (s *MarketPurchasingService) Check(ctx context.Context, itemID int64) (*MarketPurchasingCheckResponse, error) {
	var result MarketPurchasingCheckResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/check-account", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Confirm Confirm Buy
func (s *MarketPurchasingService) Confirm(ctx context.Context, itemID int64, body *MarketPurchasingConfirmBody) (*MarketPurchasingConfirmResponse, error) {
	var result MarketPurchasingConfirmResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/confirm-buy", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DiscountCancel Cancel Discount Request
func (s *MarketPurchasingService) DiscountCancel(ctx context.Context, itemID int64) (*MarketPurchasingDiscountCancelResponse, error) {
	var result MarketPurchasingDiscountCancelResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/discount", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DiscountRequest Discount Request
func (s *MarketPurchasingService) DiscountRequest(ctx context.Context, itemID int64, body *MarketPurchasingDiscountRequestBody) (*MarketPurchasingDiscountRequestResponse, error) {
	var result MarketPurchasingDiscountRequestResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/discount", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FastBuy Fast Buy Account
func (s *MarketPurchasingService) FastBuy(ctx context.Context, itemID int64, body *MarketPurchasingFastBuyBody) (*MarketPurchasingFastBuyResponse, error) {
	var result MarketPurchasingFastBuyResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/fast-buy", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
