// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketBatchService handles Market Batch API endpoints.
type MarketBatchService struct {
	client *httpClient
}

// Batch Batch
func (s *MarketBatchService) Batch(ctx context.Context, jobs []MarketBatchBatchItem) (*MarketBatchBatchResponse, error) {
	var result MarketBatchBatchResponse
	opts := requestOptions{
		Method:  "POST",
		Path:    "/batch",
		RawJSON: jobs,
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
