// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// MarketCategoryService handles Market Category API endpoints.
type MarketCategoryService struct {
	client *httpClient
}

// All Get Last Accounts
func (s *MarketCategoryService) All(ctx context.Context, params *MarketCategoryAllParams) (*MarketCategoryAllResponse, error) {
	var result MarketCategoryAllResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BattleNet BattleNet
func (s *MarketCategoryService) BattleNet(ctx context.Context, params *MarketCategoryBattleNetParams) (*MarketCategoryBattleNetResponse, error) {
	var result MarketCategoryBattleNetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/battlenet",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ChatGPT ChatGPT
func (s *MarketCategoryService) ChatGPT(ctx context.Context, params *MarketCategoryChatGPTParams) (*MarketCategoryChatGPTResponse, error) {
	var result MarketCategoryChatGPTResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/chatgpt",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Discord Discord
func (s *MarketCategoryService) Discord(ctx context.Context, params *MarketCategoryDiscordParams) (*MarketCategoryDiscordResponse, error) {
	var result MarketCategoryDiscordResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/discord",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EA EA (Origin)
func (s *MarketCategoryService) EA(ctx context.Context, params *MarketCategoryEAParams) (*MarketCategoryEAResponse, error) {
	var result MarketCategoryEAResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/ea",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EpicGames Epic Games
func (s *MarketCategoryService) EpicGames(ctx context.Context, params *MarketCategoryEpicGamesParams) (*MarketCategoryEpicGamesResponse, error) {
	var result MarketCategoryEpicGamesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/epicgames",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EscapeFromTarkov Escape from Tarkov
func (s *MarketCategoryService) EscapeFromTarkov(ctx context.Context, params *MarketCategoryEscapeFromTarkovParams) (*MarketCategoryEscapeFromTarkovResponse, error) {
	var result MarketCategoryEscapeFromTarkovResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/escape-from-tarkov",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fortnite Fortnite
func (s *MarketCategoryService) Fortnite(ctx context.Context, params *MarketCategoryFortniteParams) (*MarketCategoryFortniteResponse, error) {
	var result MarketCategoryFortniteResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/fortnite",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Games Get Category Games
func (s *MarketCategoryService) Games(ctx context.Context, categoryName string) (*MarketCategoryGamesResponse, error) {
	var result MarketCategoryGamesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%s/games", categoryName),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Gifts Gifts
func (s *MarketCategoryService) Gifts(ctx context.Context, params *MarketCategoryGiftsParams) (*MarketCategoryGiftsResponse, error) {
	var result MarketCategoryGiftsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/gifts",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Hytale Hytale
func (s *MarketCategoryService) Hytale(ctx context.Context, params *MarketCategoryHytaleParams) (*MarketCategoryHytaleResponse, error) {
	var result MarketCategoryHytaleResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/hytale",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Instagram Instagram
func (s *MarketCategoryService) Instagram(ctx context.Context, params *MarketCategoryInstagramParams) (*MarketCategoryInstagramResponse, error) {
	var result MarketCategoryInstagramResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/instagram",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Categories
func (s *MarketCategoryService) List(ctx context.Context, params *MarketCategoryListParams) (*MarketCategoryListResponse, error) {
	var result MarketCategoryListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/category",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Mihoyo miHoYo
func (s *MarketCategoryService) Mihoyo(ctx context.Context, params *MarketCategoryMihoyoParams) (*MarketCategoryMihoyoResponse, error) {
	var result MarketCategoryMihoyoResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/mihoyo",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Minecraft Minecraft
func (s *MarketCategoryService) Minecraft(ctx context.Context, params *MarketCategoryMinecraftParams) (*MarketCategoryMinecraftResponse, error) {
	var result MarketCategoryMinecraftResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/minecraft",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Params Get Category Search Params
func (s *MarketCategoryService) Params(ctx context.Context, categoryName string) (*MarketCategoryParamsResponse, error) {
	var result MarketCategoryParamsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%s/params", categoryName),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Riot Riot
func (s *MarketCategoryService) Riot(ctx context.Context, params *MarketCategoryRiotParams) (*MarketCategoryRiotResponse, error) {
	var result MarketCategoryRiotResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/riot",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Roblox Roblox
func (s *MarketCategoryService) Roblox(ctx context.Context, params *MarketCategoryRobloxParams) (*MarketCategoryRobloxResponse, error) {
	var result MarketCategoryRobloxResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/roblox",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SocialClub Social Club
func (s *MarketCategoryService) SocialClub(ctx context.Context, params *MarketCategorySocialClubParams) (*MarketCategorySocialClubResponse, error) {
	var result MarketCategorySocialClubResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/socialclub",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Steam Steam
func (s *MarketCategoryService) Steam(ctx context.Context, params *MarketCategorySteamParams) (*MarketCategorySteamResponse, error) {
	var result MarketCategorySteamResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/steam",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Supercell Supercell
func (s *MarketCategoryService) Supercell(ctx context.Context, params *MarketCategorySupercellParams) (*MarketCategorySupercellResponse, error) {
	var result MarketCategorySupercellResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/supercell",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Telegram Telegram
func (s *MarketCategoryService) Telegram(ctx context.Context, params *MarketCategoryTelegramParams) (*MarketCategoryTelegramResponse, error) {
	var result MarketCategoryTelegramResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/telegram",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TikTok TikTok
func (s *MarketCategoryService) TikTok(ctx context.Context, params *MarketCategoryTikTokParams) (*MarketCategoryTikTokResponse, error) {
	var result MarketCategoryTikTokResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/tiktok",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Uplay Uplay
func (s *MarketCategoryService) Uplay(ctx context.Context, params *MarketCategoryUplayParams) (*MarketCategoryUplayResponse, error) {
	var result MarketCategoryUplayResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/uplay",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// VPN VPN
func (s *MarketCategoryService) VPN(ctx context.Context, params *MarketCategoryVPNParams) (*MarketCategoryVPNResponse, error) {
	var result MarketCategoryVPNResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/vpn",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Warface Warface
func (s *MarketCategoryService) Warface(ctx context.Context, params *MarketCategoryWarfaceParams) (*MarketCategoryWarfaceResponse, error) {
	var result MarketCategoryWarfaceResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/warface",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Wot World of Tanks
func (s *MarketCategoryService) Wot(ctx context.Context, params *MarketCategoryWotParams) (*MarketCategoryWotResponse, error) {
	var result MarketCategoryWotResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/world-of-tanks",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WotBlitz WoT Blitz
func (s *MarketCategoryService) WotBlitz(ctx context.Context, params *MarketCategoryWotBlitzParams) (*MarketCategoryWotBlitzResponse, error) {
	var result MarketCategoryWotBlitzResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/wot-blitz",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
