// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketProfileService handles Market Profile API endpoints.
type MarketProfileService struct {
	client *httpClient
}

// Claims Get Claims
func (s *MarketProfileService) Claims(ctx context.Context, params *MarketProfileClaimsParams) (*MarketProfileClaimsResponse, error) {
	var result MarketProfileClaimsResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/claims",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Market Settings
func (s *MarketProfileService) Edit(ctx context.Context, body *MarketProfileEditBody) (*MarketProfileEditResponse, error) {
	var result MarketProfileEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/me",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Profile
func (s *MarketProfileService) Get(ctx context.Context, params *MarketProfileGetParams) (*MarketProfileGetResponse, error) {
	var result MarketProfileGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/me",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
