// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketPaymentsService handles Market Payments API endpoints.
type MarketPaymentsService struct {
	client *httpClient
}

// BalanceExchange Exchange Balance
func (s *MarketPaymentsService) BalanceExchange(ctx context.Context, body *MarketPaymentsBalanceExchangeBody) (*MarketPaymentsBalanceExchangeResponse, error) {
	var result MarketPaymentsBalanceExchangeResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/balance/exchange",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BalanceList Get List Of Balances
func (s *MarketPaymentsService) BalanceList(ctx context.Context) (*MarketPaymentsBalanceListResponse, error) {
	var result MarketPaymentsBalanceListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/balance/exchange",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Cancel Cancel Transfer
func (s *MarketPaymentsService) Cancel(ctx context.Context, body *MarketPaymentsCancelBody) (*MarketPaymentsCancelResponse, error) {
	var result MarketPaymentsCancelResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/balance/transfer/cancel",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Currency Get Currency
func (s *MarketPaymentsService) Currency(ctx context.Context) (*MarketPaymentsCurrencyResponse, error) {
	var result MarketPaymentsCurrencyResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/currency",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fee Check Transfer Fee
func (s *MarketPaymentsService) Fee(ctx context.Context, params *MarketPaymentsFeeParams) (*MarketPaymentsFeeResponse, error) {
	var result MarketPaymentsFeeResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/balance/transfer/fee",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// History Payments History
func (s *MarketPaymentsService) History(ctx context.Context, params *MarketPaymentsHistoryParams) (*MarketPaymentsHistoryResponse, error) {
	var result MarketPaymentsHistoryResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/user/payments",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceCreate Create Invoice
func (s *MarketPaymentsService) InvoiceCreate(ctx context.Context, body *MarketPaymentsInvoiceCreateBody) (*MarketPaymentsInvoiceCreateResponse, error) {
	var result MarketPaymentsInvoiceCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/invoice",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceGet Get Invoice
func (s *MarketPaymentsService) InvoiceGet(ctx context.Context, params *MarketPaymentsInvoiceGetParams) (*MarketPaymentsInvoiceGetResponse, error) {
	var result MarketPaymentsInvoiceGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/invoice",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceList Get Invoice List
func (s *MarketPaymentsService) InvoiceList(ctx context.Context, params *MarketPaymentsInvoiceListParams) (*MarketPaymentsInvoiceListResponse, error) {
	var result MarketPaymentsInvoiceListResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/invoice/list",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Payout Create Payout
func (s *MarketPaymentsService) Payout(ctx context.Context, body *MarketPaymentsPayoutBody) (*MarketPaymentsPayoutResponse, error) {
	var result MarketPaymentsPayoutResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/balance/payout",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PayoutServices Get Payout Services
func (s *MarketPaymentsService) PayoutServices(ctx context.Context) (*MarketPaymentsPayoutServicesResponse, error) {
	var result MarketPaymentsPayoutServicesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/balance/payout/services",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Transfer Transfer Money
func (s *MarketPaymentsService) Transfer(ctx context.Context, body *MarketPaymentsTransferBody) (*MarketPaymentsTransferResponse, error) {
	var result MarketPaymentsTransferResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/balance/transfer",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
