// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// MarketManagingService handles Market Managing API endpoints.
type MarketManagingService struct {
	client *httpClient
}

// AIPrice Get AI Price
func (s *MarketManagingService) AIPrice(ctx context.Context, itemID int64) (*MarketManagingAIPriceResponse, error) {
	var result MarketManagingAIPriceResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/ai-price", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBump Auto Bump
func (s *MarketManagingService) AutoBump(ctx context.Context, itemID int64, body *MarketManagingAutoBumpBody) (*MarketManagingAutoBumpResponse, error) {
	var result MarketManagingAutoBumpResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/auto-bump", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBumpDisable Disable Auto Bump
func (s *MarketManagingService) AutoBumpDisable(ctx context.Context, itemID int64) (*MarketManagingAutoBumpDisableResponse, error) {
	var result MarketManagingAutoBumpDisableResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/auto-bump", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBuyPrice Get Auto Buy Price
func (s *MarketManagingService) AutoBuyPrice(ctx context.Context, itemID int64) (*MarketManagingAutoBuyPriceResponse, error) {
	var result MarketManagingAutoBuyPriceResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/auto-buy-price", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BulkGet Bulk Get Accounts
func (s *MarketManagingService) BulkGet(ctx context.Context, body *MarketManagingBulkGetBody) (*MarketManagingBulkGetResponse, error) {
	var result MarketManagingBulkGetResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/bulk/items",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Bump Bump Account
func (s *MarketManagingService) Bump(ctx context.Context, itemID int64) (*MarketManagingBumpResponse, error) {
	var result MarketManagingBumpResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/bump", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ChangePassword Change Password
func (s *MarketManagingService) ChangePassword(ctx context.Context, itemID int64, body *MarketManagingChangePasswordBody) (*MarketManagingChangePasswordResponse, error) {
	var result MarketManagingChangePasswordResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/change-password", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CheckGuarantee Check Guarantee
func (s *MarketManagingService) CheckGuarantee(ctx context.Context, itemID int64) (*MarketManagingCheckGuaranteeResponse, error) {
	var result MarketManagingCheckGuaranteeResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/check-guarantee", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Close Close Account
func (s *MarketManagingService) Close(ctx context.Context, itemID int64) (*MarketManagingCloseResponse, error) {
	var result MarketManagingCloseResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/close", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateClaim Create Claim
func (s *MarketManagingService) CreateClaim(ctx context.Context, body *MarketManagingCreateClaimBody) (*MarketManagingCreateClaimResponse, error) {
	var result MarketManagingCreateClaimResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/claims",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeclineVideoRecording Decline Video Recording Request
func (s *MarketManagingService) DeclineVideoRecording(ctx context.Context, itemID int64, body *MarketManagingDeclineVideoRecordingBody) (*MarketManagingDeclineVideoRecordingResponse, error) {
	var result MarketManagingDeclineVideoRecordingResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/decline-video-recording", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Account
func (s *MarketManagingService) Delete(ctx context.Context, itemID int64, body *MarketManagingDeleteBody) (*MarketManagingDeleteResponse, error) {
	var result MarketManagingDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Account
func (s *MarketManagingService) Edit(ctx context.Context, itemID int64, body *MarketManagingEditBody) (*MarketManagingEditResponse, error) {
	var result MarketManagingEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/%d/edit", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EmailCode Get Email Confirmation Code
func (s *MarketManagingService) EmailCode(ctx context.Context, itemID int64) (*MarketManagingEmailCodeResponse, error) {
	var result MarketManagingEmailCodeResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/email-code", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Favorite Favorite
func (s *MarketManagingService) Favorite(ctx context.Context, itemID int64) (*MarketManagingFavoriteResponse, error) {
	var result MarketManagingFavoriteResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/star", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Account
func (s *MarketManagingService) Get(ctx context.Context, itemID int64, params *MarketManagingGetParams) (*MarketManagingGetResponse, error) {
	var result MarketManagingGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d", itemID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetLetters2 Get Email Letters
func (s *MarketManagingService) GetLetters2(ctx context.Context, params *MarketManagingGetLetters2Params) (*MarketManagingGetLetters2Response, error) {
	var result MarketManagingGetLetters2Response
	opts := requestOptions{
		Method: "GET",
		Path:   "/letters2",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Image Get Account Image
func (s *MarketManagingService) Image(ctx context.Context, itemID int64, params *MarketManagingImageParams) (*MarketManagingImageResponse, error) {
	var result MarketManagingImageResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/image", itemID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Note Edit Note
func (s *MarketManagingService) Note(ctx context.Context, itemID int64, body *MarketManagingNoteBody) (*MarketManagingNoteResponse, error) {
	var result MarketManagingNoteResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/note-save", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Open Open Account
func (s *MarketManagingService) Open(ctx context.Context, itemID int64) (*MarketManagingOpenResponse, error) {
	var result MarketManagingOpenResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/open", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PublicTag Add a Public Tag
func (s *MarketManagingService) PublicTag(ctx context.Context, itemID int64, body *MarketManagingPublicTagBody) (*MarketManagingPublicTagResponse, error) {
	var result MarketManagingPublicTagResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/public-tag", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PublicUntag Remove a Public Tag
func (s *MarketManagingService) PublicUntag(ctx context.Context, itemID int64, body *MarketManagingPublicUntagBody) (*MarketManagingPublicUntagResponse, error) {
	var result MarketManagingPublicUntagResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/public-tag", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// RefuseGuarantee Cancel Guarantee
func (s *MarketManagingService) RefuseGuarantee(ctx context.Context, itemID int64) (*MarketManagingRefuseGuaranteeResponse, error) {
	var result MarketManagingRefuseGuaranteeResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/refuse-guarantee", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamAddMafile Add Mafile
func (s *MarketManagingService) SteamAddMafile(ctx context.Context, itemID int64) (*MarketManagingSteamAddMafileResponse, error) {
	var result MarketManagingSteamAddMafileResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamGetMafile Get Mafile
func (s *MarketManagingService) SteamGetMafile(ctx context.Context, itemID int64) (*MarketManagingSteamGetMafileResponse, error) {
	var result MarketManagingSteamGetMafileResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamInventoryValue Get Account Steam Inventory Value
func (s *MarketManagingService) SteamInventoryValue(ctx context.Context, itemID int64, params *MarketManagingSteamInventoryValueParams) (*MarketManagingSteamInventoryValueResponse, error) {
	var result MarketManagingSteamInventoryValueResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/inventory-value", itemID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamMafileCode Get Mafile Confirmation Code
func (s *MarketManagingService) SteamMafileCode(ctx context.Context, itemID int64) (*MarketManagingSteamMafileCodeResponse, error) {
	var result MarketManagingSteamMafileCodeResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/guard-code", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamPreview Get Steam HTML
func (s *MarketManagingService) SteamPreview(ctx context.Context, itemID int64, params *MarketManagingSteamPreviewParams) error {
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/steam-preview", itemID),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	return s.client.request(ctx, opts, nil)
}

// SteamRemoveMafile Remove Mafile
func (s *MarketManagingService) SteamRemoveMafile(ctx context.Context, itemID int64) (*MarketManagingSteamRemoveMafileResponse, error) {
	var result MarketManagingSteamRemoveMafileResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamSDA Confirm SDA
func (s *MarketManagingService) SteamSDA(ctx context.Context, itemID int64, body *MarketManagingSteamSDABody) (*MarketManagingSteamSDAResponse, error) {
	var result MarketManagingSteamSDAResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/confirm-sda", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamUpdateValue Update Inventory Value
func (s *MarketManagingService) SteamUpdateValue(ctx context.Context, itemID int64, body *MarketManagingSteamUpdateValueBody) (*MarketManagingSteamUpdateValueResponse, error) {
	var result MarketManagingSteamUpdateValueResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/update-inventory", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamValue Get Steam Inventory Value
func (s *MarketManagingService) SteamValue(ctx context.Context, params *MarketManagingSteamValueParams) (*MarketManagingSteamValueResponse, error) {
	var result MarketManagingSteamValueResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/steam-value",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stick Stick Account
func (s *MarketManagingService) Stick(ctx context.Context, itemID int64) (*MarketManagingStickResponse, error) {
	var result MarketManagingStickResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/stick", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Tag Add a Tag
func (s *MarketManagingService) Tag(ctx context.Context, itemID int64, body *MarketManagingTagBody) (*MarketManagingTagResponse, error) {
	var result MarketManagingTagResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/tag", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TelegramCode Get Telegram Confirmation Code
func (s *MarketManagingService) TelegramCode(ctx context.Context, itemID int64) (*MarketManagingTelegramCodeResponse, error) {
	var result MarketManagingTelegramCodeResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/telegram-login-code", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TelegramResetAuth Telegram Reset Auth
func (s *MarketManagingService) TelegramResetAuth(ctx context.Context, itemID int64) (*MarketManagingTelegramResetAuthResponse, error) {
	var result MarketManagingTelegramResetAuthResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/telegram-reset-authorizations", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TempEmailPassword Get Temp Email Password
func (s *MarketManagingService) TempEmailPassword(ctx context.Context, itemID int64) (*MarketManagingTempEmailPasswordResponse, error) {
	var result MarketManagingTempEmailPasswordResponse
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/temp-email-password", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Transfer Change Account Owner
func (s *MarketManagingService) Transfer(ctx context.Context, itemID int64, body *MarketManagingTransferBody) (*MarketManagingTransferResponse, error) {
	var result MarketManagingTransferResponse
	opts := requestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/change-owner", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfavorite Unfavorite
func (s *MarketManagingService) Unfavorite(ctx context.Context, itemID int64) (*MarketManagingUnfavoriteResponse, error) {
	var result MarketManagingUnfavoriteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/star", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstick Unstick Account
func (s *MarketManagingService) Unstick(ctx context.Context, itemID int64) (*MarketManagingUnstickResponse, error) {
	var result MarketManagingUnstickResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/stick", itemID),
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Untag Remove a Tag
func (s *MarketManagingService) Untag(ctx context.Context, itemID int64, body *MarketManagingUntagBody) (*MarketManagingUntagResponse, error) {
	var result MarketManagingUntagResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/tag", itemID),
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
