// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketImapService handles Market Imap API endpoints.
type MarketImapService struct {
	client *httpClient
}

// Create Create IMAP Configuration
func (s *MarketImapService) Create(ctx context.Context, body *MarketImapCreateBody) (*MarketImapCreateResponse, error) {
	var result MarketImapCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/imap",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete IMAP Configuration
func (s *MarketImapService) Delete(ctx context.Context, body *MarketImapDeleteBody) (*MarketImapDeleteResponse, error) {
	var result MarketImapDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/imap",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
