// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketCartService handles Market Cart API endpoints.
type MarketCartService struct {
	client *httpClient
}

// Add Add Item to Cart
func (s *MarketCartService) Add(ctx context.Context, body *MarketCartAddBody) (*MarketCartAddResponse, error) {
	var result MarketCartAddResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/cart",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Item From Cart
func (s *MarketCartService) Delete(ctx context.Context, body *MarketCartDeleteBody) (*MarketCartDeleteResponse, error) {
	var result MarketCartDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/cart",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Cart Items
func (s *MarketCartService) Get(ctx context.Context, params *MarketCartGetParams) (*MarketCartGetResponse, error) {
	var result MarketCartGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/cart",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
