// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

// MarketClient provides access to the Lolzteam Market API.
type MarketClient struct {
	AutoPayments    *MarketAutoPaymentsService
	Batch           *MarketBatchService
	Cart            *MarketCartService
	Category        *MarketCategoryService
	CustomDiscounts *MarketCustomDiscountsService
	Imap            *MarketImapService
	List            *MarketListService
	Managing        *MarketManagingService
	Payments        *MarketPaymentsService
	Profile         *MarketProfileService
	Proxy           *MarketProxyService
	Publishing      *MarketPublishingService
	Purchasing      *MarketPurchasingService
}

// NewMarketClient creates a new Market API client.
func NewMarketClient(config Config) *MarketClient {
	if config.BaseURL == "" {
		config.BaseURL = "https://api.lzt.market"
	}
	if config.RequestsPerMinute == 0 {
		config.RequestsPerMinute = 120
	}
	c := newHTTPClient(config)
	return &MarketClient{
		AutoPayments:    &MarketAutoPaymentsService{client: c},
		Batch:           &MarketBatchService{client: c},
		Cart:            &MarketCartService{client: c},
		Category:        &MarketCategoryService{client: c},
		CustomDiscounts: &MarketCustomDiscountsService{client: c},
		Imap:            &MarketImapService{client: c},
		List:            &MarketListService{client: c},
		Managing:        &MarketManagingService{client: c},
		Payments:        &MarketPaymentsService{client: c},
		Profile:         &MarketProfileService{client: c},
		Proxy:           &MarketProxyService{client: c},
		Publishing:      &MarketPublishingService{client: c},
		Purchasing:      &MarketPurchasingService{client: c},
	}
}
