// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
	"fmt"
)

// MarketListService handles Market List API endpoints.
type MarketListService struct {
	client *httpClient
}

// Download Download Accounts Data
func (s *MarketListService) Download(ctx context.Context, typeVal string, params *MarketListDownloadParams) error {
	opts := requestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/user/%s/download", typeVal),
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	return s.client.request(ctx, opts, nil)
}

// Favorites Get All Favourites Accounts
func (s *MarketListService) Favorites(ctx context.Context, params *MarketListFavoritesParams) (*MarketListFavoritesResponse, error) {
	var result MarketListFavoritesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/fave",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Orders Get All Purchased Accounts
func (s *MarketListService) Orders(ctx context.Context, params *MarketListOrdersParams) (*MarketListOrdersResponse, error) {
	var result MarketListOrdersResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/user/orders",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// States Get User Items States
func (s *MarketListService) States(ctx context.Context, params *MarketListStatesParams) (*MarketListStatesResponse, error) {
	var result MarketListStatesResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/user/item-states",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// User Get All User Accounts
func (s *MarketListService) User(ctx context.Context, params *MarketListUserParams) (*MarketListUserResponse, error) {
	var result MarketListUserResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/user/items",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Viewed Get All Viewed Accounts
func (s *MarketListService) Viewed(ctx context.Context, params *MarketListViewedParams) (*MarketListViewedResponse, error) {
	var result MarketListViewedResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/viewed",
	}
	if params != nil {
		opts.Query = structToQuery(params)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
