// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketProxyService handles Market Proxy API endpoints.
type MarketProxyService struct {
	client *httpClient
}

// Add Add Proxy
func (s *MarketProxyService) Add(ctx context.Context, body *MarketProxyAddBody) (*MarketProxyAddResponse, error) {
	var result MarketProxyAddResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/proxy",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Proxy
func (s *MarketProxyService) Delete(ctx context.Context, body *MarketProxyDeleteBody) (*MarketProxyDeleteResponse, error) {
	var result MarketProxyDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/proxy",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Proxy
func (s *MarketProxyService) Get(ctx context.Context) (*MarketProxyGetResponse, error) {
	var result MarketProxyGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/proxy",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
