// Code generated by cmd/codegen. DO NOT EDIT.

package lolzteam

import (
	"context"
)

// MarketCustomDiscountsService handles Market CustomDiscounts API endpoints.
type MarketCustomDiscountsService struct {
	client *httpClient
}

// Create Create Custom Discount
func (s *MarketCustomDiscountsService) Create(ctx context.Context, body *MarketCustomDiscountsCreateBody) (*MarketCustomDiscountsCreateResponse, error) {
	var result MarketCustomDiscountsCreateResponse
	opts := requestOptions{
		Method: "POST",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Custom Discount
func (s *MarketCustomDiscountsService) Delete(ctx context.Context, body *MarketCustomDiscountsDeleteBody) (*MarketCustomDiscountsDeleteResponse, error) {
	var result MarketCustomDiscountsDeleteResponse
	opts := requestOptions{
		Method: "DELETE",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Custom Discount
func (s *MarketCustomDiscountsService) Edit(ctx context.Context, body *MarketCustomDiscountsEditBody) (*MarketCustomDiscountsEditResponse, error) {
	var result MarketCustomDiscountsEditResponse
	opts := requestOptions{
		Method: "PUT",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.Body = structToForm(body)
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Custom Discounts
func (s *MarketCustomDiscountsService) Get(ctx context.Context) (*MarketCustomDiscountsGetResponse, error) {
	var result MarketCustomDiscountsGetResponse
	opts := requestOptions{
		Method: "GET",
		Path:   "/custom-discounts",
	}
	if err := s.client.request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
