package codegen

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// APIConfig describes one API schema to generate code for.
type APIConfig struct {
	SchemaFile string
	Prefix     string
	BaseURL    string
	RPM        int
	SearchRPM  int // optional: search rate limit (e.g. 20 for Market)
}

// Generate reads OpenAPI schemas and generates Go client code.
func Generate(outDir string, apis []APIConfig) error {
	for _, api := range apis {
		data, err := os.ReadFile(filepath.Join(outDir, api.SchemaFile))
		if err != nil {
			return fmt.Errorf("reading %s: %w", api.SchemaFile, err)
		}

		g := &Generator{
			Prefix:     api.Prefix,
			Resolving:  make(map[string]bool),
			NamedTypes: make(map[string]*StructDef),
			EnumTypes:  make(map[string]*EnumDef),
			Groups:     make(map[string][]Operation),
		}

		if err := json.Unmarshal(data, &g.Spec); err != nil {
			return fmt.Errorf("parsing %s: %w", api.SchemaFile, err)
		}

		var rawSpec map[string]json.RawMessage
		if err := json.Unmarshal(data, &rawSpec); err != nil {
			return fmt.Errorf("parsing raw %s: %w", api.SchemaFile, err)
		}
		g.RawSpec = rawSpec

		g.CollectEnums()

		if err := g.ParseOperations(); err != nil {
			return fmt.Errorf("parsing operations for %s: %w", api.Prefix, err)
		}
		g.GenerateNamedTypes()

		lowerPrefix := strings.ToLower(api.Prefix)
		subDir := filepath.Join(outDir, lowerPrefix)
		if err := os.MkdirAll(subDir, 0755); err != nil {
			return fmt.Errorf("creating directory %s: %w", subDir, err)
		}

		if err := g.WriteClientFile(outDir, api.BaseURL, api.RPM, api.SearchRPM); err != nil {
			return fmt.Errorf("writing client file: %w", err)
		}

		if err := g.WriteTypesFile(outDir); err != nil {
			return fmt.Errorf("writing types file: %w", err)
		}

		fmt.Printf("Generated %s API: %d endpoints, %d groups, %d types\n",
			api.Prefix, len(g.Operations), len(g.Groups), len(g.NamedTypes))
	}
	return nil
}

// ---------------------------------------------------------------------------
// Code generation — client file
// ---------------------------------------------------------------------------

func (g *Generator) WriteClientFile(outDir, baseURL string, rpm int, searchRPM int) error {
	var b strings.Builder
	prefix := g.Prefix
	lowerPrefix := strings.ToLower(prefix)

	groupNames := SortedMapKeys(g.Groups)

	// Check if any method needs "fmt" (path params with fmt.Sprintf)
	needsFmt := false
	for _, ops := range g.Groups {
		for _, op := range ops {
			if len(op.PathParams) > 0 {
				needsFmt = true
				break
			}
		}
		if needsFmt {
			break
		}
	}

	b.WriteString("// Code generated by cmd/codegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", lowerPrefix)

	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	if needsFmt {
		b.WriteString("\t\"fmt\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\tlolzteam \"github.com/kyo-lzt/lolzteam-go\"\n")
	b.WriteString(")\n\n")

	// Client struct
	fmt.Fprintf(&b, "// Client provides access to the Lolzteam %s API.\n", prefix)
	b.WriteString("type Client struct {\n")
	for _, gn := range groupNames {
		fmt.Fprintf(&b, "\t%s *%sService\n", gn, gn)
	}
	b.WriteString("}\n\n")

	// Constructor
	fmt.Fprintf(&b, "// NewClient creates a new %s API client.\n", prefix)
	b.WriteString("func NewClient(config lolzteam.Config) (*Client, error) {\n")
	fmt.Fprintf(&b, "\tif config.BaseURL == \"\" {\n")
	fmt.Fprintf(&b, "\t\tconfig.BaseURL = %q\n", baseURL)
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tif config.RateLimit == nil {\n")
	fmt.Fprintf(&b, "\t\tconfig.RateLimit = &lolzteam.RateLimitConfig{}\n")
	fmt.Fprintf(&b, "\t}\n")
	fmt.Fprintf(&b, "\tif config.RateLimit.RequestsPerMinute == 0 {\n")
	fmt.Fprintf(&b, "\t\tconfig.RateLimit.RequestsPerMinute = %d\n", rpm)
	fmt.Fprintf(&b, "\t}\n")
	if searchRPM > 0 {
		fmt.Fprintf(&b, "\tif config.RateLimit.SearchRequestsPerMinute == 0 {\n")
		fmt.Fprintf(&b, "\t\tconfig.RateLimit.SearchRequestsPerMinute = %d\n", searchRPM)
		fmt.Fprintf(&b, "\t}\n")
	}
	fmt.Fprintf(&b, "\tif config.Retry == nil {\n")
	fmt.Fprintf(&b, "\t\tconfig.Retry = lolzteam.DefaultRetryConfig()\n")
	fmt.Fprintf(&b, "\t}\n")
	b.WriteString("\tc, err := lolzteam.NewClient(config)\n")
	fmt.Fprintf(&b, "\tif err != nil {\n")
	fmt.Fprintf(&b, "\t\treturn nil, err\n")
	fmt.Fprintf(&b, "\t}\n")
	b.WriteString("\treturn &Client{\n")
	for _, gn := range groupNames {
		fmt.Fprintf(&b, "\t\t%s: &%sService{client: c},\n", gn, gn)
	}
	b.WriteString("\t}, nil\n}\n\n")

	// Convenience constructor
	fmt.Fprintf(&b, "// NewClientFromToken creates a new %s API client with default configuration.\n", prefix)
	b.WriteString("func NewClientFromToken(token string) (*Client, error) {\n")
	b.WriteString("\treturn NewClient(lolzteam.Config{Token: token})\n")
	b.WriteString("}\n\n")

	// Service structs and methods
	for _, groupName := range groupNames {
		ops := g.Groups[groupName]
		svcName := groupName + "Service"
		fmt.Fprintf(&b, "// %s handles %s API endpoints.\n", svcName, groupName)
		fmt.Fprintf(&b, "type %s struct {\n", svcName)
		b.WriteString("\tclient *lolzteam.Client\n")
		b.WriteString("}\n\n")

		for _, op := range ops {
			g.WriteMethod(&b, groupName, op)
			b.WriteString("\n")
		}
	}

	return WriteFormattedFile(filepath.Join(outDir, lowerPrefix, "client.go"), b.String())
}

// ---------------------------------------------------------------------------
// Code generation — types file
// ---------------------------------------------------------------------------

func (g *Generator) WriteTypesFile(outDir string) error {
	lowerPrefix := strings.ToLower(g.Prefix)

	// Pre-pass: collect all response struct inline types into namedTypes
	groupNames := SortedMapKeys(g.Groups)
	for _, groupName := range groupNames {
		ops := g.Groups[groupName]
		for _, op := range ops {
			if op.HasResponse {
				structName := groupName + op.Method + "Response"
				g.CollectResponseTypes(structName, op.ResponseSchema)
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/codegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", lowerPrefix)

	// Check if any type references FileUpload (defined in root package)
	needsRootImport := g.TypesReferenceRootPkg()
	if needsRootImport {
		b.WriteString("import (\n")
		b.WriteString("\tlolzteam \"github.com/kyo-lzt/lolzteam-go\"\n")
		b.WriteString(")\n\n")
	}

	// Enum types
	enumNames := SortedMapKeys(g.EnumTypes)
	if len(enumNames) > 0 {
		for _, en := range enumNames {
			ed := g.EnumTypes[en]
			WriteEnumDef(&b, ed)
			b.WriteString("\n")
		}
	}

	// All named types (component schemas + inline response/body types)
	typeNames := SortedMapKeys(g.NamedTypes)
	for _, tn := range typeNames {
		sd := g.NamedTypes[tn]
		WriteStructDef(&b, sd)
		b.WriteString("\n")
	}

	// Params, Body, Response structs for each operation
	for _, groupName := range groupNames {
		ops := g.Groups[groupName]
		for _, op := range ops {
			// Params struct
			if len(op.QueryParams) > 0 {
				structName := groupName + op.Method + "Params"
				fmt.Fprintf(&b, "// %s holds query parameters for %s.%s.\n", structName, groupName, op.Method)
				fmt.Fprintf(&b, "type %s struct {\n", structName)
				for _, qp := range op.QueryParams {
					goType := qp.GoType
					if rootPkgTypes[goType] {
						goType = "lolzteam." + goType
					}
					desc := StripMarkdownBold(CleanComment(qp.Description))
					if desc != "" && qp.Default != "" {
						fmt.Fprintf(&b, "\t// %s - %s Default: %s\n", qp.GoName, desc, qp.Default)
					} else if desc != "" {
						fmt.Fprintf(&b, "\t// %s - %s\n", qp.GoName, desc)
					} else if qp.Default != "" {
						fmt.Fprintf(&b, "\t// %s - Default: %s\n", qp.GoName, qp.Default)
					}
					if qp.Required {
						fmt.Fprintf(&b, "\t%s %s `query:\"%s\"`\n", qp.GoName, goType, qp.Name)
					} else {
						ptrType := PtrWrap(goType)
						defaultTag := DefaultTag(qp.Default)
						fmt.Fprintf(&b, "\t%s %s `query:\"%s\"%s`\n", qp.GoName, ptrType, qp.Name, defaultTag)
					}
				}
				b.WriteString("}\n\n")
			}

			// Body struct
			if len(op.BodyProps) > 0 {
				structName := groupName + op.Method + "Body"
				fmt.Fprintf(&b, "// %s holds the request body for %s.%s.\n", structName, groupName, op.Method)
				fmt.Fprintf(&b, "type %s struct {\n", structName)
				tagName := "form"
				if op.ContentKind == ContentJSON {
					tagName = "json"
				}
				for _, bp := range op.BodyProps {
					desc := StripMarkdownBold(CleanComment(bp.Description))
					if desc != "" && bp.Default != "" {
						fmt.Fprintf(&b, "\t// %s - %s Default: %s\n", bp.GoName, desc, bp.Default)
					} else if desc != "" {
						fmt.Fprintf(&b, "\t// %s - %s\n", bp.GoName, desc)
					} else if bp.Default != "" {
						fmt.Fprintf(&b, "\t// %s - Default: %s\n", bp.GoName, bp.Default)
					}
					goType := bp.GoType
					if rootPkgTypes[goType] {
						goType = "lolzteam." + goType
					}
					if bp.Required && bp.Default == "" {
						if tagName == "json" {
							fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", bp.GoName, goType, bp.Name)
						} else {
							fmt.Fprintf(&b, "\t%s %s `form:\"%s\"`\n", bp.GoName, goType, bp.Name)
						}
					} else {
						ptrType := PtrWrap(goType)
						defaultTag := DefaultTag(bp.Default)
						if tagName == "json" {
							fmt.Fprintf(&b, "\t%s %s `json:\"%s,omitempty\"%s`\n", bp.GoName, ptrType, bp.Name, defaultTag)
						} else {
							fmt.Fprintf(&b, "\t%s %s `form:\"%s\"%s`\n", bp.GoName, ptrType, bp.Name, defaultTag)
						}
					}
				}
				b.WriteString("}\n\n")
			}

			// Discriminated union body (interface + variant structs)
			if op.BodyUnion != nil {
				WriteUnionDef(&b, op.BodyUnion, op.ContentKind)
			}

			// Array body item struct (batch endpoints)
			if op.IsArrayBody && len(op.ArrayItemProps) > 0 {
				itemName := groupName + op.Method + "Item"
				fmt.Fprintf(&b, "// %s represents a single item in the %s.%s request body.\n", itemName, groupName, op.Method)
				fmt.Fprintf(&b, "type %s struct {\n", itemName)
				for _, bp := range op.ArrayItemProps {
					if bp.Required {
						fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", bp.GoName, bp.GoType, bp.Name)
					} else {
						ptrType := PtrWrap(bp.GoType)
						fmt.Fprintf(&b, "\t%s %s `json:\"%s,omitempty\"`\n", bp.GoName, ptrType, bp.Name)
					}
				}
				b.WriteString("}\n\n")
			}

			// Response struct
			if op.HasResponse {
				structName := groupName + op.Method + "Response"
				g.WriteResponseStruct(&b, structName, op.ResponseSchema)
				b.WriteString("\n")
			}
		}
	}

	return WriteFormattedFile(filepath.Join(outDir, lowerPrefix, "models.go"), b.String())
}

// TypesReferenceRootPkg checks if any type references a root package type (FileUpload, StringOrInt).
func (g *Generator) TypesReferenceRootPkg() bool {
	rootTypes := map[string]bool{"FileUpload": true, "StringOrInt": true}
	for _, ops := range g.Groups {
		for _, op := range ops {
			for _, qp := range op.QueryParams {
				if rootTypes[qp.GoType] {
					return true
				}
			}
			for _, bp := range op.BodyProps {
				if rootTypes[bp.GoType] {
					return true
				}
			}
			if op.BodyUnion != nil {
				for _, v := range op.BodyUnion.Variants {
					for _, bp := range v.Fields {
						if rootTypes[bp.GoType] {
							return true
						}
					}
				}
			}
		}
	}
	// Check named types (component schemas) for StringOrInt fields
	for _, sd := range g.NamedTypes {
		for _, f := range sd.Fields {
			if rootTypes[f.Type.Name] {
				return true
			}
		}
	}
	// Check response schema inline fields
	for _, ops := range g.Groups {
		for _, op := range ops {
			if op.HasResponse {
				resolved := g.ResolveSchemaRef(op.ResponseSchema)
				if len(resolved.AllOf) > 0 {
					resolved = g.MergeAllOfSchemas(resolved)
				}
				if len(resolved.OneOf) > 0 || len(resolved.AnyOf) > 0 {
					resolved = g.MergeOneOfSchemas(resolved)
				}
				for _, propSchema := range resolved.Properties {
					goType := g.ResolveGoType(propSchema)
					if rootTypes[goType] {
						return true
					}
				}
			}
		}
	}
	return false
}

// CollectResponseTypes pre-registers all inline struct types from response schemas.
func (g *Generator) CollectResponseTypes(name string, s SchemaObj) {
	resolved := g.ResolveSchemaRef(s)
	if len(resolved.AllOf) > 0 {
		resolved = g.MergeAllOfSchemas(resolved)
	}
	if len(resolved.OneOf) > 0 || len(resolved.AnyOf) > 0 {
		resolved = g.MergeOneOfSchemas(resolved)
	}

	for _, propName := range SortedKeys(resolved.Properties) {
		propSchema := resolved.Properties[propName]
		goFieldName := ToPascalCase(propName)
		resolvedProp := g.ResolveSchemaRef(propSchema)
		if resolvedProp.Ref == "" && len(resolvedProp.Properties) > 0 && !allNumericKeys(resolvedProp.Properties) {
			inlineName := name + goFieldName
			inlineSD := g.SchemaToStructDef(inlineName, resolvedProp)
			g.NamedTypes[inlineName] = inlineSD
		}
	}
}

func (g *Generator) WriteResponseStruct(b *strings.Builder, name string, s SchemaObj) {
	resolved := g.ResolveSchemaRef(s)
	if len(resolved.AllOf) > 0 {
		resolved = g.MergeAllOfSchemas(resolved)
	}
	if len(resolved.OneOf) > 0 || len(resolved.AnyOf) > 0 {
		resolved = g.MergeOneOfSchemas(resolved)
	}

	reqSet := ToSet(resolved.Required)

	fmt.Fprintf(b, "// %s is the response for the endpoint.\n", name)
	fmt.Fprintf(b, "type %s struct {\n", name)

	propNames := SortedKeys(resolved.Properties)
	for _, propName := range propNames {
		propSchema := resolved.Properties[propName]
		goFieldName := ToPascalCase(propName)
		goType := g.ResolveGoType(propSchema)

		// Inline objects
		resolvedProp := g.ResolveSchemaRef(propSchema)
		if resolvedProp.Ref == "" && len(resolvedProp.Properties) > 0 {
			if allNumericKeys(resolvedProp.Properties) {
				goType = "any" // numeric-keyed objects: API may return [] or {"id":"val"}
			} else {
				inlineName := name + goFieldName
				inlineSD := g.SchemaToStructDef(inlineName, resolvedProp)
				g.NamedTypes[inlineName] = inlineSD
				goType = inlineName
			}
		}

		// Issue 2: response integer → float64
		goType = responseIntToFloat(goType)

		// Qualify root package types
		if rootPkgTypes[goType] {
			goType = "lolzteam." + goType
		}

		// Struct-typed response fields always use pointer to handle null/empty API responses
		isStruct := isStructType(goType)
		isRequired := reqSet[propName]
		if isRequired {
			if isStruct {
				fmt.Fprintf(b, "\t%s *%s `json:\"%s\"`\n", goFieldName, goType, propName)
			} else {
				fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", goFieldName, goType, propName)
			}
		} else {
			ptrType := PtrWrap(goType)
			fmt.Fprintf(b, "\t%s %s `json:\"%s,omitempty\"`\n", goFieldName, ptrType, propName)
		}
	}

	b.WriteString("}\n")
}

func (g *Generator) WriteMethod(b *strings.Builder, groupName string, op Operation) {
	svcName := groupName + "Service"
	paramsStructName := groupName + op.Method + "Params"
	bodyStructName := groupName + op.Method + "Body"
	responseStructName := groupName + op.Method + "Response"

	hasParams := len(op.QueryParams) > 0
	hasBody := len(op.BodyProps) > 0
	hasUnionBody := op.BodyUnion != nil
	itemTypeName := groupName + op.Method + "Item"

	// Build method signature
	var sigParts []string
	sigParts = append(sigParts, "ctx context.Context")
	for _, pp := range op.PathParams {
		goType := pp.GoType
		if rootPkgTypes[goType] {
			goType = "lolzteam." + goType
		}
		sigParts = append(sigParts, CamelCase(pp.GoName)+" "+goType)
	}
	if hasParams {
		sigParts = append(sigParts, "params *"+paramsStructName)
	}
	if op.IsArrayBody {
		sigParts = append(sigParts, "jobs []"+itemTypeName)
	} else if hasUnionBody {
		sigParts = append(sigParts, "body "+op.BodyUnion.InterfaceName)
	} else if hasBody {
		sigParts = append(sigParts, "body *"+bodyStructName)
	}

	returnType := "error"
	if op.IsHTMLResponse {
		returnType = "(string, error)"
	} else if op.HasResponse {
		returnType = fmt.Sprintf("(*%s, error)", responseStructName)
	}

	// Doc comment
	summary := op.Summary
	if summary == "" {
		summary = op.Method
	}
	fmt.Fprintf(b, "// %s %s\n", op.Method, StripMarkdownBold(CleanComment(summary)))
	if op.Description != "" {
		b.WriteString("//\n")
		WriteDocComment(b, op.Description, "")
	}

	fmt.Fprintf(b, "func (s *%s) %s(%s) %s {\n",
		svcName, op.Method, strings.Join(sigParts, ", "), returnType)

	// Result variable
	if op.HasResponse {
		fmt.Fprintf(b, "\tvar result %s\n", responseStructName)
	}

	// Build path
	pathExpr := BuildPathExpr(op.Path, op.PathParams)

	isSearch := strings.EqualFold(groupName, "Category")

	fmt.Fprintf(b, "\topts := lolzteam.RequestOptions{\n")
	fmt.Fprintf(b, "\t\tMethod: %q,\n", op.HTTPMethod)
	fmt.Fprintf(b, "\t\tPath:   %s,\n", pathExpr)
	if op.IsArrayBody {
		b.WriteString("\t\tRawJSON: jobs,\n")
	}
	if isSearch {
		b.WriteString("\t\tIsSearch: true,\n")
	}
	b.WriteString("\t}\n")

	if hasParams {
		b.WriteString("\tif params != nil {\n")
		b.WriteString("\t\topts.Query = lolzteam.StructToQuery(params)\n")
		b.WriteString("\t}\n")
	}

	if hasUnionBody {
		switch op.ContentKind {
		case ContentMultipart:
			b.WriteString("\tif body != nil {\n")
			b.WriteString("\t\topts.Multipart = lolzteam.StructToMultipart(body)\n")
			b.WriteString("\t}\n")
		case ContentJSON:
			b.WriteString("\tif body != nil {\n")
			b.WriteString("\t\topts.RawJSON = body\n")
			b.WriteString("\t}\n")
		default:
			b.WriteString("\tif body != nil {\n")
			b.WriteString("\t\topts.Body = lolzteam.StructToForm(body)\n")
			b.WriteString("\t}\n")
		}
	} else if !op.IsArrayBody && hasBody {
		b.WriteString("\tif body != nil {\n")
		switch op.ContentKind {
		case ContentMultipart:
			b.WriteString("\t\topts.Multipart = lolzteam.StructToMultipart(body)\n")
		case ContentJSON:
			b.WriteString("\t\topts.RawJSON = body\n")
		default:
			b.WriteString("\t\topts.Body = lolzteam.StructToForm(body)\n")
		}
		b.WriteString("\t}\n")
	}

	if op.IsHTMLResponse {
		b.WriteString("\thtml, err := s.client.RequestText(ctx, opts)\n")
		b.WriteString("\tif err != nil {\n")
		b.WriteString("\t\treturn \"\", err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn html, nil\n")
	} else if op.HasResponse {
		b.WriteString("\tif err := s.client.Request(ctx, opts, &result); err != nil {\n")
		b.WriteString("\t\treturn nil, err\n")
		b.WriteString("\t}\n")
		b.WriteString("\treturn &result, nil\n")
	} else {
		b.WriteString("\treturn s.client.Request(ctx, opts, nil)\n")
	}

	b.WriteString("}\n")
}
