// Code generated by cmd/codegen. DO NOT EDIT.

package forum

import (
	"context"
	"fmt"

	lolzteam "github.com/kyo-lzt/lolzteam-go"
)

// Client provides access to the Lolzteam Forum API.
type Client struct {
	Assets        *AssetsService
	Batch         *BatchService
	Categories    *CategoriesService
	Chatbox       *ChatboxService
	Conversations *ConversationsService
	Forms         *FormsService
	Forums        *ForumsService
	Links         *LinksService
	Navigation    *NavigationService
	Notifications *NotificationsService
	OAuth         *OAuthService
	Pages         *PagesService
	Posts         *PostsService
	ProfilePosts  *ProfilePostsService
	Search        *SearchService
	Tags          *TagsService
	Threads       *ThreadsService
	Users         *UsersService
}

// NewClient creates a new Forum API client.
func NewClient(config lolzteam.Config) (*Client, error) {
	if config.BaseURL == "" {
		config.BaseURL = "https://prod-api.lolz.live"
	}
	if config.RateLimit == nil {
		config.RateLimit = &lolzteam.RateLimitConfig{}
	}
	if config.RateLimit.RequestsPerMinute == 0 {
		config.RateLimit.RequestsPerMinute = 300
	}
	if config.Retry == nil {
		config.Retry = lolzteam.DefaultRetryConfig()
	}
	c, err := lolzteam.NewClient(config)
	if err != nil {
		return nil, err
	}
	return &Client{
		Assets:        &AssetsService{client: c},
		Batch:         &BatchService{client: c},
		Categories:    &CategoriesService{client: c},
		Chatbox:       &ChatboxService{client: c},
		Conversations: &ConversationsService{client: c},
		Forms:         &FormsService{client: c},
		Forums:        &ForumsService{client: c},
		Links:         &LinksService{client: c},
		Navigation:    &NavigationService{client: c},
		Notifications: &NotificationsService{client: c},
		OAuth:         &OAuthService{client: c},
		Pages:         &PagesService{client: c},
		Posts:         &PostsService{client: c},
		ProfilePosts:  &ProfilePostsService{client: c},
		Search:        &SearchService{client: c},
		Tags:          &TagsService{client: c},
		Threads:       &ThreadsService{client: c},
		Users:         &UsersService{client: c},
	}, nil
}

// NewClientFromToken creates a new Forum API client with default configuration.
func NewClientFromToken(token string) (*Client, error) {
	return NewClient(lolzteam.Config{Token: token})
}

// AssetsService handles Assets API endpoints.
type AssetsService struct {
	client *lolzteam.Client
}

// CSS Get CSS
//
// Gets css rulesets for requested selectors.
func (s *AssetsService) CSS(ctx context.Context, params *AssetsCSSParams) (*AssetsCSSResponse, error) {
	var result AssetsCSSResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/css",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BatchService handles Batch API endpoints.
type BatchService struct {
	client *lolzteam.Client
}

// Execute Batch
//
// Execute multiple API requests at once (Separated by comma). Maximum batch jobs is 10.
//
// Required scopes:
// + Same as called API requests.
func (s *BatchService) Execute(ctx context.Context, jobs []BatchExecuteItem) (*BatchExecuteResponse, error) {
	var result BatchExecuteResponse
	opts := lolzteam.RequestOptions{
		Method:  "POST",
		Path:    "/batch",
		RawJSON: jobs,
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CategoriesService handles Categories API endpoints.
type CategoriesService struct {
	client *lolzteam.Client
}

// Get Get Category
//
// Detail information of a category.
//
// Required scopes:
// + read
func (s *CategoriesService) Get(ctx context.Context, categoryID int64) (*CategoriesGetResponse, error) {
	var result CategoriesGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/categories/%d", categoryID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Categories
//
// List of all categories in the system.
//
// Required scopes:
// + read
func (s *CategoriesService) List(ctx context.Context, params *CategoriesListParams) (*CategoriesListResponse, error) {
	var result CategoriesListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/categories",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ChatboxService handles Chatbox API endpoints.
type ChatboxService struct {
	client *lolzteam.Client
}

// DeleteIgnore Unignore Chat User
//
// Unignore chat user.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) DeleteIgnore(ctx context.Context, body *ChatboxDeleteIgnoreBody) (*ChatboxDeleteIgnoreResponse, error) {
	var result ChatboxDeleteIgnoreResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/chatbox/ignore",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteMessage Delete Chat Message
//
// Delete chat message.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) DeleteMessage(ctx context.Context, body *ChatboxDeleteMessageBody) (*ChatboxDeleteMessageResponse, error) {
	var result ChatboxDeleteMessageResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EditMessage Edit Chat Message
//
// Edit chat message.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) EditMessage(ctx context.Context, body *ChatboxEditMessageBody) (*ChatboxEditMessageResponse, error) {
	var result ChatboxEditMessageResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetIgnore Get Ignored Chat Users
//
// Get list of ignored chat users.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) GetIgnore(ctx context.Context) (*ChatboxGetIgnoreResponse, error) {
	var result ChatboxGetIgnoreResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox/ignore",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetLeaderboard Get Chat Leaderboard
//
// Get chat leaderboard.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) GetLeaderboard(ctx context.Context, params *ChatboxGetLeaderboardParams) (*ChatboxGetLeaderboardResponse, error) {
	var result ChatboxGetLeaderboardResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/leaderboard",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetMessages Get Chat Messages
//
// Get chat messages.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) GetMessages(ctx context.Context, params *ChatboxGetMessagesParams) (*ChatboxGetMessagesResponse, error) {
	var result ChatboxGetMessagesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox/messages",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Index Get Chats
//
// Get chat rooms.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) Index(ctx context.Context, params *ChatboxIndexParams) (*ChatboxIndexResponse, error) {
	var result ChatboxIndexResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Online Get Chat Online
//
// Get chat Online Users.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) Online(ctx context.Context, params *ChatboxOnlineParams) (*ChatboxOnlineResponse, error) {
	var result ChatboxOnlineResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/online",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PostIgnore Ignore Chat User
//
// Ignore chat user.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) PostIgnore(ctx context.Context, body *ChatboxPostIgnoreBody) (*ChatboxPostIgnoreResponse, error) {
	var result ChatboxPostIgnoreResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/chatbox/ignore",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PostMessage Create Chat Message
//
// Create chat message.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) PostMessage(ctx context.Context, body *ChatboxPostMessageBody) (*ChatboxPostMessageResponse, error) {
	var result ChatboxPostMessageResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/chatbox/messages",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report Chat Message
//
// Report chat message.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) Report(ctx context.Context, body *ChatboxReportBody) (*ChatboxReportResponse, error) {
	var result ChatboxReportResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/chatbox/messages/report",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Chat Message Report Reasons
//
// Report chat message.
//
// Required scopes:
// + chatbox
func (s *ChatboxService) ReportReasons(ctx context.Context, params *ChatboxReportReasonsParams) (*ChatboxReportReasonsResponse, error) {
	var result ChatboxReportReasonsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/chatbox/messages/report",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ConversationsService handles Conversations API endpoints.
type ConversationsService struct {
	client *lolzteam.Client
}

// AlertsDisable Disable Conversation Alerts
//
// Disable alerts for conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) AlertsDisable(ctx context.Context, conversationID int64) (*ConversationsAlertsDisableResponse, error) {
	var result ConversationsAlertsDisableResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/alerts", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AlertsEnable Enable Conversation Alerts
//
// Enable alerts for conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) AlertsEnable(ctx context.Context, conversationID int64) (*ConversationsAlertsEnableResponse, error) {
	var result ConversationsAlertsEnableResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/alerts", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Conversation
//
// Create a new conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) Create(ctx context.Context, body *ConversationsCreateBody) (*ConversationsCreateResponse, error) {
	var result ConversationsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/conversations",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Leave Conversation
//
// Leave the conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) Delete(ctx context.Context, body *ConversationsDeleteBody) (*ConversationsDeleteResponse, error) {
	var result ConversationsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/conversations",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Conversation
//
// Detail information of a conversation.
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) Get(ctx context.Context, conversationID int64) (*ConversationsGetResponse, error) {
	var result ConversationsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/%d", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Invite Invite Users to Conversation
//
// Invite one or more users to an existing conversation.
//
// Required scopes:
// + conversate
// + post
func (s *ConversationsService) Invite(ctx context.Context, conversationID int64, body *ConversationsInviteBody) (*ConversationsInviteResponse, error) {
	var result ConversationsInviteResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/invite", conversationID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Kick Kick User from Conversation
//
// Kicks a user from a conversation.
//
// Required scopes:
// + conversate
func (s *ConversationsService) Kick(ctx context.Context, conversationID int64, body *ConversationsKickBody) (*ConversationsKickResponse, error) {
	var result ConversationsKickResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/kick", conversationID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Conversations
//
// List of conversations (with pagination).
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) List(ctx context.Context, params *ConversationsListParams) (*ConversationsListResponse, error) {
	var result ConversationsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/conversations",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesCreate Create Conversation Message
//
// Create a new conversation message.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) MessagesCreate(ctx context.Context, conversationID int64, body *ConversationsMessagesCreateBody) (*ConversationsMessagesCreateResponse, error) {
	var result ConversationsMessagesCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/messages", conversationID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesDelete Delete Conversation Message
//
// Deletes a message from a conversation.
//
// Required scopes:
// + conversate
func (s *ConversationsService) MessagesDelete(ctx context.Context, conversationID int64, messageID int64) (*ConversationsMessagesDeleteResponse, error) {
	var result ConversationsMessagesDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d", conversationID, messageID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesEdit Edit Conversation Message
//
// Edit a message.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) MessagesEdit(ctx context.Context, conversationID int64, messageID int64, body *ConversationsMessagesEditBody) (*ConversationsMessagesEditResponse, error) {
	var result ConversationsMessagesEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d", conversationID, messageID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesGet Get Conversation Message
//
// Detail information of a message.
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) MessagesGet(ctx context.Context, messageID int64) (*ConversationsMessagesGetResponse, error) {
	var result ConversationsMessagesGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/messages/%d", messageID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesList Get Conversation Messages
//
// List of messages in a conversation (with pagination).
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) MessagesList(ctx context.Context, conversationID int64, params *ConversationsMessagesListParams) (*ConversationsMessagesListResponse, error) {
	var result ConversationsMessagesListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/conversations/%d/messages", conversationID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesStick Stick Conversation Message
//
// Stick a message in a conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) MessagesStick(ctx context.Context, conversationID int64, messageID int64) (*ConversationsMessagesStickResponse, error) {
	var result ConversationsMessagesStickResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d/stick", conversationID, messageID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// MessagesUnstick Unstick Conversation Message
//
// Unstick a message in a conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) MessagesUnstick(ctx context.Context, conversationID int64, messageID int64) (*ConversationsMessagesUnstickResponse, error) {
	var result ConversationsMessagesUnstickResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/messages/%d/stick", conversationID, messageID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Read Read a Conversation
//
// Read a specific conversation.
//
// Required scopes:
// + conversate
func (s *ConversationsService) Read(ctx context.Context, conversationID int64) (*ConversationsReadResponse, error) {
	var result ConversationsReadResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/read", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReadAll Read All Conversations
//
// Mark all conversations as read.
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) ReadAll(ctx context.Context) (*ConversationsReadAllResponse, error) {
	var result ConversationsReadAllResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/conversations/read-all",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Save Send Content To Saved Messages
//
// Send content to Saved Messages.
//
// Required scopes:
// + conversate
func (s *ConversationsService) Save(ctx context.Context, body *ConversationsSaveBody) (*ConversationsSaveResponse, error) {
	var result ConversationsSaveResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/conversations/save",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Search Search Conversations Messages
//
// Search for conversations messages or recipients.
//
// Required scopes:
// + read
// + conversate
func (s *ConversationsService) Search(ctx context.Context, body *ConversationsSearchBody) (*ConversationsSearchResponse, error) {
	var result ConversationsSearchResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/conversations/search",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Star Star Conversation
//
// Star conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) Star(ctx context.Context, conversationID int64) (*ConversationsStarResponse, error) {
	var result ConversationsStarResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/conversations/%d/star", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Start Start Conversation
//
// Start a new conversation with a user.
//
// Required scopes:
// + conversate
func (s *ConversationsService) Start(ctx context.Context, body *ConversationsStartBody) (*ConversationsStartResponse, error) {
	var result ConversationsStartResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/conversations/start",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstar Unstar Conversation
//
// Unstar conversation.
//
// Required scopes:
// + post
// + conversate
func (s *ConversationsService) Unstar(ctx context.Context, conversationID int64) (*ConversationsUnstarResponse, error) {
	var result ConversationsUnstarResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/conversations/%d/star", conversationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Update Edit Conversation
//
// Edit conversation.
//
// Required scopes:
// + conversate
func (s *ConversationsService) Update(ctx context.Context, body *ConversationsUpdateBody) (*ConversationsUpdateResponse, error) {
	var result ConversationsUpdateResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/conversations",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FormsService handles Forms API endpoints.
type FormsService struct {
	client *lolzteam.Client
}

// Create Create Form
//
// Create Form.
func (s *FormsService) Create(ctx context.Context, body FormsCreateBody) (*FormsCreateResponse, error) {
	var result FormsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/forms/save",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Forms List
//
// Get Forms List
func (s *FormsService) List(ctx context.Context, params *FormsListParams) (*FormsListResponse, error) {
	var result FormsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/forms",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ForumsService handles Forums API endpoints.
type ForumsService struct {
	client *lolzteam.Client
}

// EditFeedOptions Edit Feed Options
//
// Edit feed options.
//
// Required scopes:
// + post
func (s *ForumsService) EditFeedOptions(ctx context.Context, body *ForumsEditFeedOptionsBody) (*ForumsEditFeedOptionsResponse, error) {
	var result ForumsEditFeedOptionsResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/forums/feed/options",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow Forum
//
// Follow a forum.
//
// Required scopes:
// + post
func (s *ForumsService) Follow(ctx context.Context, forumID int64, body *ForumsFollowBody) (*ForumsFollowResponse, error) {
	var result ForumsFollowResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followed Get Followed Forums
//
// List of followed forums by current user.
//
// Required scopes:
// + read
func (s *ForumsService) Followed(ctx context.Context, params *ForumsFollowedParams) (*ForumsFollowedResponse, error) {
	var result ForumsFollowedResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/forums/followed",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get Followers
//
// List of a forum's followers. For privacy reason, only the current user will be included in the list (if the user follows the specified forum).
//
// Required scopes:
// + read
func (s *ForumsService) Followers(ctx context.Context, forumID int64) (*ForumsFollowersResponse, error) {
	var result ForumsFollowersResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Forum
//
// Detail information of a forum.
//
// Required scopes:
// + read
func (s *ForumsService) Get(ctx context.Context, forumID int64) (*ForumsGetResponse, error) {
	var result ForumsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/forums/%d", forumID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetFeedOptions Get Feed Options
//
// Returns available options for the forums feed.
//
// Required scopes:
// + read
func (s *ForumsService) GetFeedOptions(ctx context.Context) (*ForumsGetFeedOptionsResponse, error) {
	var result ForumsGetFeedOptionsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/forums/feed/options",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Grouped Get Forums Tree
//
// Returns grouped forums.
//
// Required scopes:
// + read
func (s *ForumsService) Grouped(ctx context.Context) (*ForumsGroupedResponse, error) {
	var result ForumsGroupedResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/forums/grouped",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Forums
//
// List of all forums in the system.
//
// Required scopes:
// + read
func (s *ForumsService) List(ctx context.Context, params *ForumsListParams) (*ForumsListResponse, error) {
	var result ForumsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/forums",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow Forum
//
// Unfollow a forum.
//
// Required scopes:
// + post
func (s *ForumsService) Unfollow(ctx context.Context, forumID int64) (*ForumsUnfollowResponse, error) {
	var result ForumsUnfollowResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/forums/%d/followers", forumID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// LinksService handles Links API endpoints.
type LinksService struct {
	client *lolzteam.Client
}

// Get Get Link Forum
//
// Detail information of a link forum.
//
// Required scopes:
// + read
func (s *LinksService) Get(ctx context.Context, linkID int64) (*LinksGetResponse, error) {
	var result LinksGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/link-forums/%d", linkID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Links Forum
//
// List of all link forums.
//
// Required scopes:
// + read
func (s *LinksService) List(ctx context.Context) (*LinksListResponse, error) {
	var result LinksListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/link-forums",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// NavigationService handles Navigation API endpoints.
type NavigationService struct {
	client *lolzteam.Client
}

// List Get Navigation
//
// List of navigation elements within the system.
//
// Required scopes:
// + read
func (s *NavigationService) List(ctx context.Context, params *NavigationListParams) (*NavigationListResponse, error) {
	var result NavigationListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/navigation",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// NotificationsService handles Notifications API endpoints.
type NotificationsService struct {
	client *lolzteam.Client
}

// Get Get Notification
//
// Get associated content of notification. The response depends on the content type.
//
// Required scopes:
// + read
func (s *NotificationsService) Get(ctx context.Context, notificationID int64) (*NotificationsGetResponse, error) {
	var result NotificationsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/notifications/%d/content", notificationID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Notifications
//
// List of notifications (both read and unread).
//
// Required scopes:
// + read
func (s *NotificationsService) List(ctx context.Context, params *NotificationsListParams) (*NotificationsListResponse, error) {
	var result NotificationsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/notifications",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Read Mark Notification Read
//
// Mark single notification or all existing notifications read.
//
// Required scopes:
// + post
func (s *NotificationsService) Read(ctx context.Context, body *NotificationsReadBody) (*NotificationsReadResponse, error) {
	var result NotificationsReadResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/notifications/read",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// OAuthService handles OAuth API endpoints.
type OAuthService struct {
	client *lolzteam.Client
}

// Token Get Access Token
//
// Obtain an access token using various grant types.
//
// Supports the following grant types:
// - Client Credentials
// - Authorization Code
// - Refresh Token
// - Password
func (s *OAuthService) Token(ctx context.Context, body OAuthTokenBody) (*OAuthTokenResponse, error) {
	var result OAuthTokenResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/oauth/token",
	}
	if body != nil {
		opts.Multipart = lolzteam.StructToMultipart(body)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PagesService handles Pages API endpoints.
type PagesService struct {
	client *lolzteam.Client
}

// Get Get Page
//
// Detail information of a page.
//
// Required scopes:
// + read
func (s *PagesService) Get(ctx context.Context, pageID int64) (*PagesGetResponse, error) {
	var result PagesGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/pages/%d", pageID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Pages
//
// List of all pages in the system.
//
// Required scopes:
// + read
func (s *PagesService) List(ctx context.Context, params *PagesListParams) (*PagesListResponse, error) {
	var result PagesListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/pages",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PostsService handles Posts API endpoints.
type PostsService struct {
	client *lolzteam.Client
}

// CommentsCreate Create Post Comment
//
// Create a post comment.
//
// Required scopes:
// + post
func (s *PostsService) CommentsCreate(ctx context.Context, body *PostsCommentsCreateBody) (*PostsCommentsCreateResponse, error) {
	var result PostsCommentsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsDelete Delete Post Comment
//
// Delete a post comment.
//
// Required scopes:
// + post
func (s *PostsService) CommentsDelete(ctx context.Context, body *PostsCommentsDeleteBody) (*PostsCommentsDeleteResponse, error) {
	var result PostsCommentsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsEdit Edit Post Comment
//
// Edit a post comment.
//
// Required scopes:
// + post
func (s *PostsService) CommentsEdit(ctx context.Context, body *PostsCommentsEditBody) (*PostsCommentsEditResponse, error) {
	var result PostsCommentsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsGet Get Post Comments
//
// List of post comments in a thread.
//
// Required scopes:
// + read
func (s *PostsService) CommentsGet(ctx context.Context, params *PostsCommentsGetParams) (*PostsCommentsGetResponse, error) {
	var result PostsCommentsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/posts/comments",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsReport Report Post Comment
//
// Report a post comment.
//
// Required scopes:
// + post
func (s *PostsService) CommentsReport(ctx context.Context, body *PostsCommentsReportBody) (*PostsCommentsReportResponse, error) {
	var result PostsCommentsReportResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/posts/comments/report",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Post
//
// Create a new post.
//
// Required scopes:
// + post
func (s *PostsService) Create(ctx context.Context, body *PostsCreateBody) (*PostsCreateResponse, error) {
	var result PostsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/posts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Post
//
// Delete a post.
//
// Required scopes:
// + post
func (s *PostsService) Delete(ctx context.Context, postID int64, body *PostsDeleteBody) (*PostsDeleteResponse, error) {
	var result PostsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Post
//
// Edit a post.
//
// Required scopes:
// + post
func (s *PostsService) Edit(ctx context.Context, postID int64, body *PostsEditBody) (*PostsEditResponse, error) {
	var result PostsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Post
//
// Detail information of a post.
//
// Required scopes:
// + read
func (s *PostsService) Get(ctx context.Context, postID int64) (*PostsGetResponse, error) {
	var result PostsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d", postID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Like Like Post
//
// Like a post.
//
// Required scopes:
// + post
func (s *PostsService) Like(ctx context.Context, postID int64) (*PostsLikeResponse, error) {
	var result PostsLikeResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get Post Likes
//
// List of users who liked a post.
//
// Required scopes:
// + read
func (s *PostsService) Likes(ctx context.Context, postID int64, params *PostsLikesParams) (*PostsLikesResponse, error) {
	var result PostsLikesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Posts
//
// List of posts in a thread (with pagination).
//
// Required scopes:
// + read
func (s *PostsService) List(ctx context.Context, params *PostsListParams) (*PostsListResponse, error) {
	var result PostsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/posts",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report Post
//
// Report a post.
//
// Required scopes:
// + post
func (s *PostsService) Report(ctx context.Context, postID int64, body *PostsReportBody) (*PostsReportResponse, error) {
	var result PostsReportResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/posts/%d/report", postID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Post Report Reasons
//
// Get post report reasons.
//
// Required scopes:
// + read
func (s *PostsService) ReportReasons(ctx context.Context, postID int64) (*PostsReportReasonsResponse, error) {
	var result PostsReportReasonsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/posts/%d/report", postID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unlike Unlike Post
//
// Unlike a post.
//
// Required scopes:
// + post
func (s *PostsService) Unlike(ctx context.Context, postID int64) (*PostsUnlikeResponse, error) {
	var result PostsUnlikeResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/posts/%d/likes", postID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ProfilePostsService handles ProfilePosts API endpoints.
type ProfilePostsService struct {
	client *lolzteam.Client
}

// CommentsCreate Create Profile Post Comment
//
// Create a new profile post comment.
//
// Required scopes:
// + post
func (s *ProfilePostsService) CommentsCreate(ctx context.Context, body *ProfilePostsCommentsCreateBody) (*ProfilePostsCommentsCreateResponse, error) {
	var result ProfilePostsCommentsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsDelete Delete Profile Post Comment
//
// Delete a profile post comment.
//
// Required scopes:
// + post
func (s *ProfilePostsService) CommentsDelete(ctx context.Context, body *ProfilePostsCommentsDeleteBody) (*ProfilePostsCommentsDeleteResponse, error) {
	var result ProfilePostsCommentsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsEdit Edit Profile Post Comment
//
// Edit a profile post comment.
//
// Required scopes:
// + post
func (s *ProfilePostsService) CommentsEdit(ctx context.Context, body *ProfilePostsCommentsEditBody) (*ProfilePostsCommentsEditResponse, error) {
	var result ProfilePostsCommentsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/profile-posts/comments",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsGet Get Profile Post Comment
//
// Detail information of a profile post comment.
//
// Required scopes:
// + read
func (s *ProfilePostsService) CommentsGet(ctx context.Context, profilePostID int64, commentID int64) (*ProfilePostsCommentsGetResponse, error) {
	var result ProfilePostsCommentsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/comments/%d", profilePostID, commentID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsList Get Profile Post Comments
//
// List of comments of a profile post.
//
// Required scopes:
// + read
func (s *ProfilePostsService) CommentsList(ctx context.Context, params *ProfilePostsCommentsListParams) (*ProfilePostsCommentsListResponse, error) {
	var result ProfilePostsCommentsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/profile-posts/comments",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CommentsReport Report a Profile Post Comment
//
// Report a profile post comment.
//
// Required scopes:
// + post
func (s *ProfilePostsService) CommentsReport(ctx context.Context, commentID int64, body *ProfilePostsCommentsReportBody) (*ProfilePostsCommentsReportResponse, error) {
	var result ProfilePostsCommentsReportResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/comments/%d/report", commentID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Profile Post
//
// Create a profile post on a user profile.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Create(ctx context.Context, body *ProfilePostsCreateBody) (*ProfilePostsCreateResponse, error) {
	var result ProfilePostsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/profile-posts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Profile Post
//
// Delete a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Delete(ctx context.Context, profilePostID int64, params *ProfilePostsDeleteParams) (*ProfilePostsDeleteResponse, error) {
	var result ProfilePostsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Profile Post
//
// Edit a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Edit(ctx context.Context, profilePostID int64, body *ProfilePostsEditBody) (*ProfilePostsEditResponse, error) {
	var result ProfilePostsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Profile Post
//
// Detail information of a profile post.
//
// Required scopes:
// + read
func (s *ProfilePostsService) Get(ctx context.Context, profilePostID int64) (*ProfilePostsGetResponse, error) {
	var result ProfilePostsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Like Like Profile Post
//
// Like a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Like(ctx context.Context, profilePostID int64) (*ProfilePostsLikeResponse, error) {
	var result ProfilePostsLikeResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get Profile Post Likes
//
// List of users who liked a profile post.
//
// Required scopes:
// + read
func (s *ProfilePostsService) Likes(ctx context.Context, profilePostID int64) (*ProfilePostsLikesResponse, error) {
	var result ProfilePostsLikesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Profile Posts
//
// List of profile posts (with pagination).
//
// Required scopes:
// + read
func (s *ProfilePostsService) List(ctx context.Context, userID lolzteam.StringOrInt, params *ProfilePostsListParams) (*ProfilePostsListResponse, error) {
	var result ProfilePostsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/profile-posts", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Report Report a Profile Post
//
// Report a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Report(ctx context.Context, profilePostID int64, body *ProfilePostsReportBody) (*ProfilePostsReportResponse, error) {
	var result ProfilePostsReportResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/report", profilePostID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ReportReasons Get Profile Post Report Reasons
//
// Get Profile Post Report Reasons.
//
// Required scopes:
// + read
func (s *ProfilePostsService) ReportReasons(ctx context.Context, profilePostID int64) (*ProfilePostsReportReasonsResponse, error) {
	var result ProfilePostsReportReasonsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/profile-posts/%d/report", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stick Stick Profile Post
//
// Stick a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Stick(ctx context.Context, profilePostID int64) (*ProfilePostsStickResponse, error) {
	var result ProfilePostsStickResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/profile-posts/%d/stick", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unlike Unlike Profile Post
//
// Unlike a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Unlike(ctx context.Context, profilePostID int64) (*ProfilePostsUnlikeResponse, error) {
	var result ProfilePostsUnlikeResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d/likes", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstick Unstick Profile Post
//
// Unstick a profile post.
//
// Required scopes:
// + post
func (s *ProfilePostsService) Unstick(ctx context.Context, profilePostID int64) (*ProfilePostsUnstickResponse, error) {
	var result ProfilePostsUnstickResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/profile-posts/%d/stick", profilePostID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SearchService handles Search API endpoints.
type SearchService struct {
	client *lolzteam.Client
}

// All Search
//
// Search for all supported contents.
//
// Required scopes:
// + post
func (s *SearchService) All(ctx context.Context, body *SearchAllBody) (*SearchAllResponse, error) {
	var result SearchAllResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Posts Search Post
//
// Search for posts.
//
// Required scopes:
// + post
func (s *SearchService) Posts(ctx context.Context, body *SearchPostsBody) (*SearchPostsResponse, error) {
	var result SearchPostsResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search/posts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ProfilePosts Search Profile Posts
//
// Search for profile posts.
//
// Required scopes:
// + post
func (s *SearchService) ProfilePosts(ctx context.Context, body *SearchProfilePostsBody) (*SearchProfilePostsResponse, error) {
	var result SearchProfilePostsResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search/profile-posts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Results Get Search Results
//
// List of search results (with pagination).
//
// Required scopes:
// + get
func (s *SearchService) Results(ctx context.Context, searchID lolzteam.StringOrInt, params *SearchResultsParams) (*SearchResultsResponse, error) {
	var result SearchResultsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/search/%s/results", searchID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Tagged Search Tagged
//
// Search for tagged contents.
//
// Required scopes:
// + post
func (s *SearchService) Tagged(ctx context.Context, body *SearchTaggedBody) (*SearchTaggedResponse, error) {
	var result SearchTaggedResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search/tagged",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Threads Search Thread
//
// Search for threads.
//
// Required scopes:
// + post
func (s *SearchService) Threads(ctx context.Context, body *SearchThreadsBody) (*SearchThreadsResponse, error) {
	var result SearchThreadsResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search/threads",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Users Search Users
//
// Search for users.
//
// Required scopes:
// + post
func (s *SearchService) Users(ctx context.Context, body *SearchUsersBody) (*SearchUsersResponse, error) {
	var result SearchUsersResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/search/users",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TagsService handles Tags API endpoints.
type TagsService struct {
	client *lolzteam.Client
}

// Find Get Filtered Content
//
// Filtered list of tags.
//
// Required scopes:
// + read
func (s *TagsService) Find(ctx context.Context, params *TagsFindParams) (*TagsFindResponse, error) {
	var result TagsFindResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/tags/find",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Tagged Content
//
// List of tagged contents.
//
// Required scopes:
// + read
func (s *TagsService) Get(ctx context.Context, tagID int64, params *TagsGetParams) (*TagsGetResponse, error) {
	var result TagsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/tags/%d", tagID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Tags
//
// List of tags.
//
// Required scopes:
// + read
func (s *TagsService) List(ctx context.Context, params *TagsListParams) (*TagsListResponse, error) {
	var result TagsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/tags/list",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Popular Get Popular Tags
//
// List of popular tags (no pagination).
//
// Required scopes:
// + read
func (s *TagsService) Popular(ctx context.Context) (*TagsPopularResponse, error) {
	var result TagsPopularResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/tags",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ThreadsService handles Threads API endpoints.
type ThreadsService struct {
	client *lolzteam.Client
}

// Bump Bump Thread
//
// Bump a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Bump(ctx context.Context, threadID int64) (*ThreadsBumpResponse, error) {
	var result ThreadsBumpResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/bump", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Claim Create Claim
//
// Create a Claim.
//
// Required scopes:
// + post
func (s *ThreadsService) Claim(ctx context.Context, body *ThreadsClaimBody) (*ThreadsClaimResponse, error) {
	var result ThreadsClaimResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/claims",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Create Create Thread
//
// Create a new thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Create(ctx context.Context, body *ThreadsCreateBody) (*ThreadsCreateResponse, error) {
	var result ThreadsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/threads",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateContest Create Contest
//
// Create a new contest.
//
// Required scopes:
// + post
func (s *ThreadsService) CreateContest(ctx context.Context, body *ThreadsCreateContestBody) (*ThreadsCreateContestResponse, error) {
	var result ThreadsCreateContestResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/contests",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Thread
//
// Delete a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Delete(ctx context.Context, threadID int64, body *ThreadsDeleteBody) (*ThreadsDeleteResponse, error) {
	var result ThreadsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit thread
//
// Edit a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Edit(ctx context.Context, threadID int64, body *ThreadsEditBody) (*ThreadsEditResponse, error) {
	var result ThreadsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Finish Finish Contest
//
// Finishes a contest.
//
// Required scopes:
// + post
func (s *ThreadsService) Finish(ctx context.Context, threadID int64) (*ThreadsFinishResponse, error) {
	var result ThreadsFinishResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/contests/%d/finish", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow Thread
//
// Follow a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Follow(ctx context.Context, threadID int64, body *ThreadsFollowBody) (*ThreadsFollowResponse, error) {
	var result ThreadsFollowResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followed Get Followed Threads
//
// List of followed threads by current user.
//
// Required scopes:
// + read
func (s *ThreadsService) Followed(ctx context.Context, params *ThreadsFollowedParams) (*ThreadsFollowedResponse, error) {
	var result ThreadsFollowedResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/threads/followed",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get Thread Followers
//
// List of a thread's followers. For privacy reason, only the current user will be included in the list.
//
// Required scopes:
// + read
func (s *ThreadsService) Followers(ctx context.Context, threadID int64) (*ThreadsFollowersResponse, error) {
	var result ThreadsFollowersResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Thread
//
// Detail information of a thread.
//
// Required scopes:
// + read
func (s *ThreadsService) Get(ctx context.Context, threadID int64, params *ThreadsGetParams) (*ThreadsGetResponse, error) {
	var result ThreadsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d", threadID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Hide Hide Thread
//
// Hide a thread from your feed.
//
// Required scopes:
// + post
func (s *ThreadsService) Hide(ctx context.Context, threadID int64) (*ThreadsHideResponse, error) {
	var result ThreadsHideResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/hide", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Threads
//
// List of threads in a forum (with pagination).
//
// Required scopes:
// + read
func (s *ThreadsService) List(ctx context.Context, params *ThreadsListParams) (*ThreadsListResponse, error) {
	var result ThreadsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/threads",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Move Move Thread
//
// Move a thread to another forum.
//
// Required scopes:
// + post
func (s *ThreadsService) Move(ctx context.Context, threadID int64, body *ThreadsMoveBody) (*ThreadsMoveResponse, error) {
	var result ThreadsMoveResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/move", threadID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Navigation Get Navigation Elements
//
// List of navigation elements to reach the specified thread.
//
// Required scopes:
// + read
func (s *ThreadsService) Navigation(ctx context.Context, threadID int64) (*ThreadsNavigationResponse, error) {
	var result ThreadsNavigationResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/navigation", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PollGet Get Poll
//
// Detail information of a poll.
//
// Required scopes:
// + read
func (s *ThreadsService) PollGet(ctx context.Context, threadID int64) (*ThreadsPollGetResponse, error) {
	var result ThreadsPollGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/threads/%d/poll", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PollVote Vote Poll
//
// Vote on a thread poll.
//
// Required scopes:
// + post
func (s *ThreadsService) PollVote(ctx context.Context, threadID int64, body *ThreadsPollVoteBody) (*ThreadsPollVoteResponse, error) {
	var result ThreadsPollVoteResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/poll/votes", threadID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Recent Get Recent Threads
//
// List of recent threads.
//
// Required scopes:
// + read
func (s *ThreadsService) Recent(ctx context.Context, params *ThreadsRecentParams) (*ThreadsRecentResponse, error) {
	var result ThreadsRecentResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/threads/recent",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Star Bookmark Thread
//
// Bookmark a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Star(ctx context.Context, threadID int64) (*ThreadsStarResponse, error) {
	var result ThreadsStarResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/threads/%d/star", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow Thread
//
// Unfollow a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Unfollow(ctx context.Context, threadID int64) (*ThreadsUnfollowResponse, error) {
	var result ThreadsUnfollowResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d/followers", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unread Get Unread Threads
//
// List of unread threads (must be logged in).
//
// Required scopes:
// + read
func (s *ThreadsService) Unread(ctx context.Context, params *ThreadsUnreadParams) (*ThreadsUnreadResponse, error) {
	var result ThreadsUnreadResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/threads/new",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstar Unbookmark Thread
//
// Unbookmark a thread.
//
// Required scopes:
// + post
func (s *ThreadsService) Unstar(ctx context.Context, threadID int64) (*ThreadsUnstarResponse, error) {
	var result ThreadsUnstarResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/threads/%d/star", threadID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UsersService handles Users API endpoints.
type UsersService struct {
	client *lolzteam.Client
}

// AvatarCrop Crop Avatar
//
// Crop avatar for a user.
//
// Required scopes:
// + post
func (s *UsersService) AvatarCrop(ctx context.Context, userID lolzteam.StringOrInt, body *UsersAvatarCropBody) (*UsersAvatarCropResponse, error) {
	var result UsersAvatarCropResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/avatar/crop", userID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AvatarDelete Delete Avatar
//
// Delete avatar for a user.
//
// Required scopes:
// + post
func (s *UsersService) AvatarDelete(ctx context.Context, userID lolzteam.StringOrInt) (*UsersAvatarDeleteResponse, error) {
	var result UsersAvatarDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%s/avatar", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AvatarUpload Upload Avatar
//
// Upload avatar for a user.
//
// Required scopes:
// + post
func (s *UsersService) AvatarUpload(ctx context.Context, userID lolzteam.StringOrInt, body *UsersAvatarUploadBody) (*UsersAvatarUploadResponse, error) {
	var result UsersAvatarUploadResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/avatar", userID),
	}
	if body != nil {
		opts.Multipart = lolzteam.StructToMultipart(body)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundCrop Crop Background
//
// Crop background for a user.
//
// Required scopes:
// + post
func (s *UsersService) BackgroundCrop(ctx context.Context, userID lolzteam.StringOrInt, body *UsersBackgroundCropBody) (*UsersBackgroundCropResponse, error) {
	var result UsersBackgroundCropResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/background/crop", userID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundDelete Delete Background
//
// Delete background for a user.
//
// Required scopes:
// + post
func (s *UsersService) BackgroundDelete(ctx context.Context, userID lolzteam.StringOrInt) (*UsersBackgroundDeleteResponse, error) {
	var result UsersBackgroundDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%s/background", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BackgroundUpload Upload Background
//
// Upload background for a user.
//
// Required scopes:
// + post
func (s *UsersService) BackgroundUpload(ctx context.Context, userID lolzteam.StringOrInt, body *UsersBackgroundUploadBody) (*UsersBackgroundUploadResponse, error) {
	var result UsersBackgroundUploadResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/background", userID),
	}
	if body != nil {
		opts.Multipart = lolzteam.StructToMultipart(body)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Claims Get User Claims
//
// Get user claims.
//
// Required scopes:
// + read
func (s *UsersService) Claims(ctx context.Context, userID lolzteam.StringOrInt, params *UsersClaimsParams) (*UsersClaimsResponse, error) {
	var result UsersClaimsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/claims", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Contents Get Contents
//
// List of contents created by user (with pagination).
//
// Required scopes:
// + read
func (s *UsersService) Contents(ctx context.Context, userID lolzteam.StringOrInt, params *UsersContentsParams) (*UsersContentsResponse, error) {
	var result UsersContentsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/timeline", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit User
//
// Edit a user.
//
// Required scopes:
// + post
func (s *UsersService) Edit(ctx context.Context, userID lolzteam.StringOrInt, body *UsersEditBody) (*UsersEditResponse, error) {
	var result UsersEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/users/%s", userID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fields Get User Fields
//
// List of user fields.
//
// Required scopes:
// + read
func (s *UsersService) Fields(ctx context.Context) (*UsersFieldsResponse, error) {
	var result UsersFieldsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/users/fields",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Find Find Users
//
// List of users filtered by username, email or custom fields.
//
// Required scopes:
// + read
func (s *UsersService) Find(ctx context.Context, params *UsersFindParams) (*UsersFindResponse, error) {
	var result UsersFindResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/users/find",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Follow Follow User
//
// Follow a user.
//
// Required scopes:
// + post
func (s *UsersService) Follow(ctx context.Context, userID lolzteam.StringOrInt) (*UsersFollowResponse, error) {
	var result UsersFollowResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/followers", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followers Get User Followers
//
// List of a user's followers.
//
// Required scopes:
// + read
func (s *UsersService) Followers(ctx context.Context, userID lolzteam.StringOrInt, params *UsersFollowersParams) (*UsersFollowersResponse, error) {
	var result UsersFollowersResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/followers", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Followings Get Followed Users By User
//
// List of users whom are followed by a user.
//
// Required scopes:
// + read
func (s *UsersService) Followings(ctx context.Context, userID lolzteam.StringOrInt, params *UsersFollowingsParams) (*UsersFollowingsResponse, error) {
	var result UsersFollowingsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/followings", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get User
//
// Detail information of a user.
//
// Required scopes:
// + read
// + basic
func (s *UsersService) Get(ctx context.Context, userID lolzteam.StringOrInt, params *UsersGetParams) (*UsersGetResponse, error) {
	var result UsersGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ignore Ignore User
//
// Ignore a user.
//
// Required scopes:
// + post
func (s *UsersService) Ignore(ctx context.Context, userID lolzteam.StringOrInt) (*UsersIgnoreResponse, error) {
	var result UsersIgnoreResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/users/%s/ignore", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// IgnoreEdit Edit Ignoring Options
//
// Edit ignoring options.
//
// Required scopes:
// + post
func (s *UsersService) IgnoreEdit(ctx context.Context, userID lolzteam.StringOrInt, params *UsersIgnoreEditParams) (*UsersIgnoreEditResponse, error) {
	var result UsersIgnoreEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/users/%s/ignore", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Ignored Get Ignored Users
//
// List of ignored users of current user.
//
// Required scopes:
// + read
func (s *UsersService) Ignored(ctx context.Context, params *UsersIgnoredParams) (*UsersIgnoredResponse, error) {
	var result UsersIgnoredResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/users/ignored",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Likes Get User Likes
//
// Get information about user likes.
//
// Required scopes:
// + read
func (s *UsersService) Likes(ctx context.Context, userID lolzteam.StringOrInt, params *UsersLikesParams) (*UsersLikesResponse, error) {
	var result UsersLikesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/likes", userID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Users
//
// List of users (with pagination).
//
// Required scopes:
// + read
func (s *UsersService) List(ctx context.Context, params *UsersListParams) (*UsersListResponse, error) {
	var result UsersListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/users",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SACancelReset Cancel Secret Answer Reset
//
// Cancel a pending secret answer reset request for the account.
//
// Required scopes:
// + post
func (s *UsersService) SACancelReset(ctx context.Context) (*UsersSACancelResetResponse, error) {
	var result UsersSACancelResetResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/account/secret-answer/reset",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SAReset Reset Secret Answer
//
// Request a reset of the secret answer for the account.
//
// Required scopes:
// + post
func (s *UsersService) SAReset(ctx context.Context) (*UsersSAResetResponse, error) {
	var result UsersSAResetResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/account/secret-answer/reset",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SecretAnswerTypes Get Secret Answer Types
//
// Get available secret answer types for user account security.
//
// Required scopes:
// + read
func (s *UsersService) SecretAnswerTypes(ctx context.Context) (*UsersSecretAnswerTypesResponse, error) {
	var result UsersSecretAnswerTypesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/users/secret-answer/types",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Trophies Get Trophies
//
// List of user trophies.
//
// Required scopes:
// + read
func (s *UsersService) Trophies(ctx context.Context, userID lolzteam.StringOrInt) (*UsersTrophiesResponse, error) {
	var result UsersTrophiesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/users/%s/trophies", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfollow Unfollow User
//
// Unfollow a user.
//
// Required scopes:
// + post
func (s *UsersService) Unfollow(ctx context.Context, userID lolzteam.StringOrInt) (*UsersUnfollowResponse, error) {
	var result UsersUnfollowResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%s/followers", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unignore Unignore User
//
// Stop ignoring a user.
//
// Required scopes:
// + post
func (s *UsersService) Unignore(ctx context.Context, userID lolzteam.StringOrInt) (*UsersUnignoreResponse, error) {
	var result UsersUnignoreResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/users/%s/ignore", userID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
