// Code generated by cmd/codegen. DO NOT EDIT.

package market

import (
	"context"
	"fmt"

	lolzteam "github.com/kyo-lzt/lolzteam-go"
)

// Client provides access to the Lolzteam Market API.
type Client struct {
	AutoPayments    *AutoPaymentsService
	Batch           *BatchService
	Cart            *CartService
	Category        *CategoryService
	CustomDiscounts *CustomDiscountsService
	Imap            *ImapService
	List            *ListService
	Managing        *ManagingService
	Payments        *PaymentsService
	Profile         *ProfileService
	Proxy           *ProxyService
	Publishing      *PublishingService
	Purchasing      *PurchasingService
}

// NewClient creates a new Market API client.
func NewClient(config lolzteam.Config) (*Client, error) {
	if config.BaseURL == "" {
		config.BaseURL = "https://prod-api.lzt.market"
	}
	if config.RateLimit == nil {
		config.RateLimit = &lolzteam.RateLimitConfig{}
	}
	if config.RateLimit.RequestsPerMinute == 0 {
		config.RateLimit.RequestsPerMinute = 120
	}
	if config.RateLimit.SearchRequestsPerMinute == 0 {
		config.RateLimit.SearchRequestsPerMinute = 20
	}
	if config.Retry == nil {
		config.Retry = lolzteam.DefaultRetryConfig()
	}
	c, err := lolzteam.NewClient(config)
	if err != nil {
		return nil, err
	}
	return &Client{
		AutoPayments:    &AutoPaymentsService{client: c},
		Batch:           &BatchService{client: c},
		Cart:            &CartService{client: c},
		Category:        &CategoryService{client: c},
		CustomDiscounts: &CustomDiscountsService{client: c},
		Imap:            &ImapService{client: c},
		List:            &ListService{client: c},
		Managing:        &ManagingService{client: c},
		Payments:        &PaymentsService{client: c},
		Profile:         &ProfileService{client: c},
		Proxy:           &ProxyService{client: c},
		Publishing:      &PublishingService{client: c},
		Purchasing:      &PurchasingService{client: c},
	}, nil
}

// NewClientFromToken creates a new Market API client with default configuration.
func NewClientFromToken(token string) (*Client, error) {
	return NewClient(lolzteam.Config{Token: token})
}

// AutoPaymentsService handles AutoPayments API endpoints.
type AutoPaymentsService struct {
	client *lolzteam.Client
}

// Create Create Auto Payment
func (s *AutoPaymentsService) Create(ctx context.Context, body *AutoPaymentsCreateBody) (*AutoPaymentsCreateResponse, error) {
	var result AutoPaymentsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/auto-payment",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Auto Payment
func (s *AutoPaymentsService) Delete(ctx context.Context, body *AutoPaymentsDeleteBody) (*AutoPaymentsDeleteResponse, error) {
	var result AutoPaymentsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/auto-payment",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Auto Payments
func (s *AutoPaymentsService) List(ctx context.Context) (*AutoPaymentsListResponse, error) {
	var result AutoPaymentsListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/auto-payments",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BatchService handles Batch API endpoints.
type BatchService struct {
	client *lolzteam.Client
}

// Batch Batch
func (s *BatchService) Batch(ctx context.Context, jobs []BatchBatchItem) (*BatchBatchResponse, error) {
	var result BatchBatchResponse
	opts := lolzteam.RequestOptions{
		Method:  "POST",
		Path:    "/batch",
		RawJSON: jobs,
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CartService handles Cart API endpoints.
type CartService struct {
	client *lolzteam.Client
}

// Add Add Item to Cart
func (s *CartService) Add(ctx context.Context, body *CartAddBody) (*CartAddResponse, error) {
	var result CartAddResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/cart",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Item From Cart
func (s *CartService) Delete(ctx context.Context, body *CartDeleteBody) (*CartDeleteResponse, error) {
	var result CartDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/cart",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Cart Items
func (s *CartService) Get(ctx context.Context, params *CartGetParams) (*CartGetResponse, error) {
	var result CartGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/cart",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CategoryService handles Category API endpoints.
type CategoryService struct {
	client *lolzteam.Client
}

// All Get Last Accounts
func (s *CategoryService) All(ctx context.Context, params *CategoryAllParams) (*CategoryAllResponse, error) {
	var result CategoryAllResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BattleNet BattleNet
func (s *CategoryService) BattleNet(ctx context.Context, params *CategoryBattleNetParams) (*CategoryBattleNetResponse, error) {
	var result CategoryBattleNetResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/battlenet",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ChatGPT ChatGPT
func (s *CategoryService) ChatGPT(ctx context.Context, params *CategoryChatGPTParams) (*CategoryChatGPTResponse, error) {
	var result CategoryChatGPTResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/chatgpt",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Discord Discord
func (s *CategoryService) Discord(ctx context.Context, params *CategoryDiscordParams) (*CategoryDiscordResponse, error) {
	var result CategoryDiscordResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/discord",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EA EA (Origin)
func (s *CategoryService) EA(ctx context.Context, params *CategoryEAParams) (*CategoryEAResponse, error) {
	var result CategoryEAResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/ea",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EpicGames Epic Games
func (s *CategoryService) EpicGames(ctx context.Context, params *CategoryEpicGamesParams) (*CategoryEpicGamesResponse, error) {
	var result CategoryEpicGamesResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/epicgames",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EscapeFromTarkov Escape from Tarkov
func (s *CategoryService) EscapeFromTarkov(ctx context.Context, params *CategoryEscapeFromTarkovParams) (*CategoryEscapeFromTarkovResponse, error) {
	var result CategoryEscapeFromTarkovResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/escape-from-tarkov",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fortnite Fortnite
func (s *CategoryService) Fortnite(ctx context.Context, params *CategoryFortniteParams) (*CategoryFortniteResponse, error) {
	var result CategoryFortniteResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/fortnite",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Games Get Category Games
func (s *CategoryService) Games(ctx context.Context, categoryName string) (*CategoryGamesResponse, error) {
	var result CategoryGamesResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     fmt.Sprintf("/%s/games", categoryName),
		IsSearch: true,
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Gifts Gifts
func (s *CategoryService) Gifts(ctx context.Context, params *CategoryGiftsParams) (*CategoryGiftsResponse, error) {
	var result CategoryGiftsResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/gifts",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Hytale Hytale
func (s *CategoryService) Hytale(ctx context.Context, params *CategoryHytaleParams) (*CategoryHytaleResponse, error) {
	var result CategoryHytaleResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/hytale",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Instagram Instagram
func (s *CategoryService) Instagram(ctx context.Context, params *CategoryInstagramParams) (*CategoryInstagramResponse, error) {
	var result CategoryInstagramResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/instagram",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// List Get Categories
func (s *CategoryService) List(ctx context.Context, params *CategoryListParams) (*CategoryListResponse, error) {
	var result CategoryListResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/category",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Mihoyo miHoYo
func (s *CategoryService) Mihoyo(ctx context.Context, params *CategoryMihoyoParams) (*CategoryMihoyoResponse, error) {
	var result CategoryMihoyoResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/mihoyo",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Minecraft Minecraft
func (s *CategoryService) Minecraft(ctx context.Context, params *CategoryMinecraftParams) (*CategoryMinecraftResponse, error) {
	var result CategoryMinecraftResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/minecraft",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Params Get Category Search Params
func (s *CategoryService) Params(ctx context.Context, categoryName string) (*CategoryParamsResponse, error) {
	var result CategoryParamsResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     fmt.Sprintf("/%s/params", categoryName),
		IsSearch: true,
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Riot Riot
func (s *CategoryService) Riot(ctx context.Context, params *CategoryRiotParams) (*CategoryRiotResponse, error) {
	var result CategoryRiotResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/riot",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Roblox Roblox
func (s *CategoryService) Roblox(ctx context.Context, params *CategoryRobloxParams) (*CategoryRobloxResponse, error) {
	var result CategoryRobloxResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/roblox",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SocialClub Social Club
func (s *CategoryService) SocialClub(ctx context.Context, params *CategorySocialClubParams) (*CategorySocialClubResponse, error) {
	var result CategorySocialClubResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/socialclub",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Steam Steam
func (s *CategoryService) Steam(ctx context.Context, params *CategorySteamParams) (*CategorySteamResponse, error) {
	var result CategorySteamResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/steam",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Supercell Supercell
func (s *CategoryService) Supercell(ctx context.Context, params *CategorySupercellParams) (*CategorySupercellResponse, error) {
	var result CategorySupercellResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/supercell",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Telegram Telegram
func (s *CategoryService) Telegram(ctx context.Context, params *CategoryTelegramParams) (*CategoryTelegramResponse, error) {
	var result CategoryTelegramResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/telegram",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TikTok TikTok
func (s *CategoryService) TikTok(ctx context.Context, params *CategoryTikTokParams) (*CategoryTikTokResponse, error) {
	var result CategoryTikTokResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/tiktok",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Uplay Uplay
func (s *CategoryService) Uplay(ctx context.Context, params *CategoryUplayParams) (*CategoryUplayResponse, error) {
	var result CategoryUplayResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/uplay",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// VPN VPN
func (s *CategoryService) VPN(ctx context.Context, params *CategoryVPNParams) (*CategoryVPNResponse, error) {
	var result CategoryVPNResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/vpn",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Warface Warface
func (s *CategoryService) Warface(ctx context.Context, params *CategoryWarfaceParams) (*CategoryWarfaceResponse, error) {
	var result CategoryWarfaceResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/warface",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Wot World of Tanks
func (s *CategoryService) Wot(ctx context.Context, params *CategoryWotParams) (*CategoryWotResponse, error) {
	var result CategoryWotResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/world-of-tanks",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// WotBlitz WoT Blitz
func (s *CategoryService) WotBlitz(ctx context.Context, params *CategoryWotBlitzParams) (*CategoryWotBlitzResponse, error) {
	var result CategoryWotBlitzResponse
	opts := lolzteam.RequestOptions{
		Method:   "GET",
		Path:     "/wot-blitz",
		IsSearch: true,
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CustomDiscountsService handles CustomDiscounts API endpoints.
type CustomDiscountsService struct {
	client *lolzteam.Client
}

// Create Create Custom Discount
func (s *CustomDiscountsService) Create(ctx context.Context, body *CustomDiscountsCreateBody) (*CustomDiscountsCreateResponse, error) {
	var result CustomDiscountsCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Custom Discount
func (s *CustomDiscountsService) Delete(ctx context.Context, body *CustomDiscountsDeleteBody) (*CustomDiscountsDeleteResponse, error) {
	var result CustomDiscountsDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Custom Discount
func (s *CustomDiscountsService) Edit(ctx context.Context, body *CustomDiscountsEditBody) (*CustomDiscountsEditResponse, error) {
	var result CustomDiscountsEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/custom-discounts",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Custom Discounts
func (s *CustomDiscountsService) Get(ctx context.Context) (*CustomDiscountsGetResponse, error) {
	var result CustomDiscountsGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/custom-discounts",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ImapService handles Imap API endpoints.
type ImapService struct {
	client *lolzteam.Client
}

// Create Create IMAP Configuration
func (s *ImapService) Create(ctx context.Context, body *ImapCreateBody) (*ImapCreateResponse, error) {
	var result ImapCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/imap",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete IMAP Configuration
func (s *ImapService) Delete(ctx context.Context, body *ImapDeleteBody) (*ImapDeleteResponse, error) {
	var result ImapDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/imap",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ListService handles List API endpoints.
type ListService struct {
	client *lolzteam.Client
}

// Download Download Accounts Data
func (s *ListService) Download(ctx context.Context, typeVal string, params *ListDownloadParams) (string, error) {
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/user/%s/download", typeVal),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	html, err := s.client.RequestText(ctx, opts)
	if err != nil {
		return "", err
	}
	return html, nil
}

// Favorites Get All Favourites Accounts
func (s *ListService) Favorites(ctx context.Context, params *ListFavoritesParams) (*ListFavoritesResponse, error) {
	var result ListFavoritesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/fave",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Orders Get All Purchased Accounts
func (s *ListService) Orders(ctx context.Context, params *ListOrdersParams) (*ListOrdersResponse, error) {
	var result ListOrdersResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/user/orders",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// States Get User Items States
func (s *ListService) States(ctx context.Context, params *ListStatesParams) (*ListStatesResponse, error) {
	var result ListStatesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/user/item-states",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// User Get All User Accounts
func (s *ListService) User(ctx context.Context, params *ListUserParams) (*ListUserResponse, error) {
	var result ListUserResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/user/items",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Viewed Get All Viewed Accounts
func (s *ListService) Viewed(ctx context.Context, params *ListViewedParams) (*ListViewedResponse, error) {
	var result ListViewedResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/viewed",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ManagingService handles Managing API endpoints.
type ManagingService struct {
	client *lolzteam.Client
}

// AIPrice Get AI Price
func (s *ManagingService) AIPrice(ctx context.Context, itemID int64) (*ManagingAIPriceResponse, error) {
	var result ManagingAIPriceResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/ai-price", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBump Auto Bump
func (s *ManagingService) AutoBump(ctx context.Context, itemID int64, body *ManagingAutoBumpBody) (*ManagingAutoBumpResponse, error) {
	var result ManagingAutoBumpResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/auto-bump", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBumpDisable Disable Auto Bump
func (s *ManagingService) AutoBumpDisable(ctx context.Context, itemID int64) (*ManagingAutoBumpDisableResponse, error) {
	var result ManagingAutoBumpDisableResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/auto-bump", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// AutoBuyPrice Get Auto Buy Price
func (s *ManagingService) AutoBuyPrice(ctx context.Context, itemID int64) (*ManagingAutoBuyPriceResponse, error) {
	var result ManagingAutoBuyPriceResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/auto-buy-price", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BulkGet Bulk Get Accounts
func (s *ManagingService) BulkGet(ctx context.Context, body *ManagingBulkGetBody) (*ManagingBulkGetResponse, error) {
	var result ManagingBulkGetResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/bulk/items",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Bump Bump Account
func (s *ManagingService) Bump(ctx context.Context, itemID int64) (*ManagingBumpResponse, error) {
	var result ManagingBumpResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/bump", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ChangePassword Change Password
func (s *ManagingService) ChangePassword(ctx context.Context, itemID int64, body *ManagingChangePasswordBody) (*ManagingChangePasswordResponse, error) {
	var result ManagingChangePasswordResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/change-password", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CheckGuarantee Check Guarantee
func (s *ManagingService) CheckGuarantee(ctx context.Context, itemID int64) (*ManagingCheckGuaranteeResponse, error) {
	var result ManagingCheckGuaranteeResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/check-guarantee", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Close Close Account
func (s *ManagingService) Close(ctx context.Context, itemID int64) (*ManagingCloseResponse, error) {
	var result ManagingCloseResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/close", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateClaim Create Claim
func (s *ManagingService) CreateClaim(ctx context.Context, body *ManagingCreateClaimBody) (*ManagingCreateClaimResponse, error) {
	var result ManagingCreateClaimResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/claims",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeclineVideoRecording Decline Video Recording Request
func (s *ManagingService) DeclineVideoRecording(ctx context.Context, itemID int64, body *ManagingDeclineVideoRecordingBody) (*ManagingDeclineVideoRecordingResponse, error) {
	var result ManagingDeclineVideoRecordingResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/decline-video-recording", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Account
func (s *ManagingService) Delete(ctx context.Context, itemID int64, body *ManagingDeleteBody) (*ManagingDeleteResponse, error) {
	var result ManagingDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Account
func (s *ManagingService) Edit(ctx context.Context, itemID int64, body *ManagingEditBody) (*ManagingEditResponse, error) {
	var result ManagingEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   fmt.Sprintf("/%d/edit", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// EmailCode Get Email Confirmation Code
func (s *ManagingService) EmailCode(ctx context.Context, itemID int64) (*ManagingEmailCodeResponse, error) {
	var result ManagingEmailCodeResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/email-code", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Favorite Favorite
func (s *ManagingService) Favorite(ctx context.Context, itemID int64) (*ManagingFavoriteResponse, error) {
	var result ManagingFavoriteResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/star", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Account
func (s *ManagingService) Get(ctx context.Context, itemID int64, params *ManagingGetParams) (*ManagingGetResponse, error) {
	var result ManagingGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d", itemID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// GetLetters2 Get Email Letters
func (s *ManagingService) GetLetters2(ctx context.Context, params *ManagingGetLetters2Params) (*ManagingGetLetters2Response, error) {
	var result ManagingGetLetters2Response
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/letters2",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Image Get Account Image
func (s *ManagingService) Image(ctx context.Context, itemID int64, params *ManagingImageParams) (*ManagingImageResponse, error) {
	var result ManagingImageResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/image", itemID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Note Edit Note
func (s *ManagingService) Note(ctx context.Context, itemID int64, body *ManagingNoteBody) (*ManagingNoteResponse, error) {
	var result ManagingNoteResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/note-save", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Open Open Account
func (s *ManagingService) Open(ctx context.Context, itemID int64) (*ManagingOpenResponse, error) {
	var result ManagingOpenResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/open", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PublicTag Add a Public Tag
func (s *ManagingService) PublicTag(ctx context.Context, itemID int64, body *ManagingPublicTagBody) (*ManagingPublicTagResponse, error) {
	var result ManagingPublicTagResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/public-tag", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PublicUntag Remove a Public Tag
func (s *ManagingService) PublicUntag(ctx context.Context, itemID int64, body *ManagingPublicUntagBody) (*ManagingPublicUntagResponse, error) {
	var result ManagingPublicUntagResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/public-tag", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// RefuseGuarantee Cancel Guarantee
func (s *ManagingService) RefuseGuarantee(ctx context.Context, itemID int64) (*ManagingRefuseGuaranteeResponse, error) {
	var result ManagingRefuseGuaranteeResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/refuse-guarantee", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamAddMafile Add Mafile
func (s *ManagingService) SteamAddMafile(ctx context.Context, itemID int64) (*ManagingSteamAddMafileResponse, error) {
	var result ManagingSteamAddMafileResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamGetMafile Get Mafile
func (s *ManagingService) SteamGetMafile(ctx context.Context, itemID int64) (*ManagingSteamGetMafileResponse, error) {
	var result ManagingSteamGetMafileResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamInventoryValue Get Account Steam Inventory Value
func (s *ManagingService) SteamInventoryValue(ctx context.Context, itemID int64, params *ManagingSteamInventoryValueParams) (*ManagingSteamInventoryValueResponse, error) {
	var result ManagingSteamInventoryValueResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/inventory-value", itemID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamMafileCode Get Mafile Confirmation Code
func (s *ManagingService) SteamMafileCode(ctx context.Context, itemID int64) (*ManagingSteamMafileCodeResponse, error) {
	var result ManagingSteamMafileCodeResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/guard-code", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamPreview Get Steam HTML
func (s *ManagingService) SteamPreview(ctx context.Context, itemID int64, params *ManagingSteamPreviewParams) (string, error) {
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/steam-preview", itemID),
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	html, err := s.client.RequestText(ctx, opts)
	if err != nil {
		return "", err
	}
	return html, nil
}

// SteamRemoveMafile Remove Mafile
func (s *ManagingService) SteamRemoveMafile(ctx context.Context, itemID int64) (*ManagingSteamRemoveMafileResponse, error) {
	var result ManagingSteamRemoveMafileResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/mafile", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamSDA Confirm SDA
func (s *ManagingService) SteamSDA(ctx context.Context, itemID int64, body *ManagingSteamSDABody) (*ManagingSteamSDAResponse, error) {
	var result ManagingSteamSDAResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/confirm-sda", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamUpdateValue Update Inventory Value
func (s *ManagingService) SteamUpdateValue(ctx context.Context, itemID int64, body *ManagingSteamUpdateValueBody) (*ManagingSteamUpdateValueResponse, error) {
	var result ManagingSteamUpdateValueResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/update-inventory", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// SteamValue Get Steam Inventory Value
func (s *ManagingService) SteamValue(ctx context.Context, params *ManagingSteamValueParams) (*ManagingSteamValueResponse, error) {
	var result ManagingSteamValueResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/steam-value",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Stick Stick Account
func (s *ManagingService) Stick(ctx context.Context, itemID int64) (*ManagingStickResponse, error) {
	var result ManagingStickResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/stick", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Tag Add a Tag
func (s *ManagingService) Tag(ctx context.Context, itemID int64, body *ManagingTagBody) (*ManagingTagResponse, error) {
	var result ManagingTagResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/tag", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TelegramCode Get Telegram Confirmation Code
func (s *ManagingService) TelegramCode(ctx context.Context, itemID int64) (*ManagingTelegramCodeResponse, error) {
	var result ManagingTelegramCodeResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/telegram-login-code", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TelegramResetAuth Telegram Reset Auth
func (s *ManagingService) TelegramResetAuth(ctx context.Context, itemID int64) (*ManagingTelegramResetAuthResponse, error) {
	var result ManagingTelegramResetAuthResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/telegram-reset-authorizations", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// TempEmailPassword Get Temp Email Password
func (s *ManagingService) TempEmailPassword(ctx context.Context, itemID int64) (*ManagingTempEmailPasswordResponse, error) {
	var result ManagingTempEmailPasswordResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   fmt.Sprintf("/%d/temp-email-password", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Transfer Change Account Owner
func (s *ManagingService) Transfer(ctx context.Context, itemID int64, body *ManagingTransferBody) (*ManagingTransferResponse, error) {
	var result ManagingTransferResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/change-owner", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unfavorite Unfavorite
func (s *ManagingService) Unfavorite(ctx context.Context, itemID int64) (*ManagingUnfavoriteResponse, error) {
	var result ManagingUnfavoriteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/star", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Unstick Unstick Account
func (s *ManagingService) Unstick(ctx context.Context, itemID int64) (*ManagingUnstickResponse, error) {
	var result ManagingUnstickResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/stick", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Untag Remove a Tag
func (s *ManagingService) Untag(ctx context.Context, itemID int64, body *ManagingUntagBody) (*ManagingUntagResponse, error) {
	var result ManagingUntagResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/tag", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PaymentsService handles Payments API endpoints.
type PaymentsService struct {
	client *lolzteam.Client
}

// BalanceExchange Exchange Balance
func (s *PaymentsService) BalanceExchange(ctx context.Context, body *PaymentsBalanceExchangeBody) (*PaymentsBalanceExchangeResponse, error) {
	var result PaymentsBalanceExchangeResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/balance/exchange",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// BalanceList Get List Of Balances
func (s *PaymentsService) BalanceList(ctx context.Context) (*PaymentsBalanceListResponse, error) {
	var result PaymentsBalanceListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/balance/exchange",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Cancel Cancel Transfer
func (s *PaymentsService) Cancel(ctx context.Context, body *PaymentsCancelBody) (*PaymentsCancelResponse, error) {
	var result PaymentsCancelResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/balance/transfer/cancel",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Currency Get Currency
func (s *PaymentsService) Currency(ctx context.Context) (*PaymentsCurrencyResponse, error) {
	var result PaymentsCurrencyResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/currency",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Fee Check Transfer Fee
func (s *PaymentsService) Fee(ctx context.Context, params *PaymentsFeeParams) (*PaymentsFeeResponse, error) {
	var result PaymentsFeeResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/balance/transfer/fee",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// History Payments History
func (s *PaymentsService) History(ctx context.Context, params *PaymentsHistoryParams) (*PaymentsHistoryResponse, error) {
	var result PaymentsHistoryResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/user/payments",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceCreate Create Invoice
func (s *PaymentsService) InvoiceCreate(ctx context.Context, body *PaymentsInvoiceCreateBody) (*PaymentsInvoiceCreateResponse, error) {
	var result PaymentsInvoiceCreateResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/invoice",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceGet Get Invoice
func (s *PaymentsService) InvoiceGet(ctx context.Context, params *PaymentsInvoiceGetParams) (*PaymentsInvoiceGetResponse, error) {
	var result PaymentsInvoiceGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/invoice",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// InvoiceList Get Invoice List
func (s *PaymentsService) InvoiceList(ctx context.Context, params *PaymentsInvoiceListParams) (*PaymentsInvoiceListResponse, error) {
	var result PaymentsInvoiceListResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/invoice/list",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Payout Create Payout
func (s *PaymentsService) Payout(ctx context.Context, body *PaymentsPayoutBody) (*PaymentsPayoutResponse, error) {
	var result PaymentsPayoutResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/balance/payout",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PayoutServices Get Payout Services
func (s *PaymentsService) PayoutServices(ctx context.Context) (*PaymentsPayoutServicesResponse, error) {
	var result PaymentsPayoutServicesResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/balance/payout/services",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Transfer Transfer Money
func (s *PaymentsService) Transfer(ctx context.Context, body *PaymentsTransferBody) (*PaymentsTransferResponse, error) {
	var result PaymentsTransferResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/balance/transfer",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ProfileService handles Profile API endpoints.
type ProfileService struct {
	client *lolzteam.Client
}

// Claims Get Claims
func (s *ProfileService) Claims(ctx context.Context, params *ProfileClaimsParams) (*ProfileClaimsResponse, error) {
	var result ProfileClaimsResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/claims",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Edit Edit Market Settings
func (s *ProfileService) Edit(ctx context.Context, body *ProfileEditBody) (*ProfileEditResponse, error) {
	var result ProfileEditResponse
	opts := lolzteam.RequestOptions{
		Method: "PUT",
		Path:   "/me",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Profile
func (s *ProfileService) Get(ctx context.Context, params *ProfileGetParams) (*ProfileGetResponse, error) {
	var result ProfileGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/me",
	}
	if params != nil {
		opts.Query = lolzteam.StructToQuery(params)
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// ProxyService handles Proxy API endpoints.
type ProxyService struct {
	client *lolzteam.Client
}

// Add Add Proxy
func (s *ProxyService) Add(ctx context.Context, body *ProxyAddBody) (*ProxyAddResponse, error) {
	var result ProxyAddResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/proxy",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Delete Delete Proxy
func (s *ProxyService) Delete(ctx context.Context, body *ProxyDeleteBody) (*ProxyDeleteResponse, error) {
	var result ProxyDeleteResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   "/proxy",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Get Get Proxy
func (s *ProxyService) Get(ctx context.Context) (*ProxyGetResponse, error) {
	var result ProxyGetResponse
	opts := lolzteam.RequestOptions{
		Method: "GET",
		Path:   "/proxy",
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PublishingService handles Publishing API endpoints.
type PublishingService struct {
	client *lolzteam.Client
}

// Add Add Account
func (s *PublishingService) Add(ctx context.Context, body *PublishingAddBody) (*PublishingAddResponse, error) {
	var result PublishingAddResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/item/add",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Check Check Account Details
func (s *PublishingService) Check(ctx context.Context, itemID int64, body *PublishingCheckBody) (*PublishingCheckResponse, error) {
	var result PublishingCheckResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/goods/check", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// External Add an External Account
func (s *PublishingService) External(ctx context.Context, itemID int64, body *PublishingExternalBody) (*PublishingExternalResponse, error) {
	var result PublishingExternalResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/external-account", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FastSell Fast Account Upload
func (s *PublishingService) FastSell(ctx context.Context, body *PublishingFastSellBody) (*PublishingFastSellResponse, error) {
	var result PublishingFastSellResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   "/item/fast-sell",
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PurchasingService handles Purchasing API endpoints.
type PurchasingService struct {
	client *lolzteam.Client
}

// Check Check Account
func (s *PurchasingService) Check(ctx context.Context, itemID int64) (*PurchasingCheckResponse, error) {
	var result PurchasingCheckResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/check-account", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// Confirm Confirm Buy
func (s *PurchasingService) Confirm(ctx context.Context, itemID int64, body *PurchasingConfirmBody) (*PurchasingConfirmResponse, error) {
	var result PurchasingConfirmResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/confirm-buy", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DiscountCancel Cancel Discount Request
func (s *PurchasingService) DiscountCancel(ctx context.Context, itemID int64) (*PurchasingDiscountCancelResponse, error) {
	var result PurchasingDiscountCancelResponse
	opts := lolzteam.RequestOptions{
		Method: "DELETE",
		Path:   fmt.Sprintf("/%d/discount", itemID),
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DiscountRequest Discount Request
func (s *PurchasingService) DiscountRequest(ctx context.Context, itemID int64, body *PurchasingDiscountRequestBody) (*PurchasingDiscountRequestResponse, error) {
	var result PurchasingDiscountRequestResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/discount", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// FastBuy Fast Buy Account
func (s *PurchasingService) FastBuy(ctx context.Context, itemID int64, body *PurchasingFastBuyBody) (*PurchasingFastBuyResponse, error) {
	var result PurchasingFastBuyResponse
	opts := lolzteam.RequestOptions{
		Method: "POST",
		Path:   fmt.Sprintf("/%d/fast-buy", itemID),
	}
	if body != nil {
		opts.RawJSON = body
	}
	if err := s.client.Request(ctx, opts, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
